export const globalCopy = {
  brand: "HeyPubli",
  tagline: "Professional micro-creator platform",
  nav: {
    home: "Home",
    calendar: "Calendar",
    analytics: "Analytics",
    settings: "Settings",
  },
  adminNav: {
    overview: "Overview",
    influencers: "Creators",
    scheduler: "Scheduler",
    messages: "Messages",
    brands: "Brands",
    hotmart: "Hotmart",
    settings: "Settings",
  },
  auth: {
    login: "Log in",
    signup: "Sign up",
    logout: "Log out",
    forgotPassword: "Forgot your password?",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    next: "Next",
    back: "Back",
    loading: "Loading...",
    error: "Something went wrong",
    success: "Success!",
    delete: "Delete",
    edit: "Edit",
    search: "Search",
    filter: "Filter",
    noResults: "No results found",
  },
  status: {
    connected: "Connected",
    pending: "Pending",
    active: "Active",
    inactive: "Inactive",
    published: "Published",
    scheduled: "Scheduled",
    failed: "Failed",
  },
  footer: {
    copyright: "© 2026 HeyPubli. All rights reserved.",
  },
} as const;
