// Verified 30 September 2026 against Hostunico owner release 4e51e24:
// src/core/hostunico/domain.ts, apps/hostunico/src/legal.ts and report copy.
// Experience, payouts and coverage: Hostunico University curriculum, release
// 41eefb3. Hugo's current pricing and call instructions override older copy.
// Hugo confirmed brand-first answers and no public office visits on 1 October 2026.
export const HOSTUNICO_COMPANY = {
  brand: 'Hostunico',
  legalName: 'ULINC UNICO GROUP LTD.',
  companyNumber: '11197856',
  registeredAddress: '483 Green Lanes, London, England, N13 4BS',
  website: 'https://hostunico.com',
  supportEmail: 'hello@hostunico.com',
  registry: 'https://find-and-update.company-information.service.gov.uk/company/11197856',
} as const;

export const HOSTUNICO_COMPANY_ANSWERS = [
  { key: 'company-registration', title: 'Registered company name, only when asked', match: /\b(registered (?:company|name)|legal (?:name|entity)|what (?:company )?name are you registered under)\b/i, supersedes: ['identity'], say: `The registered company is ${HOSTUNICO_COMPANY.legalName}` },
  { key: 'company-number', title: 'Company number or Companies House, only when asked', match: /\b(company (?:registration )?number|registration number|registered company number|companies house)\b/i, supersedes: ['identity', 'company-registration'], say: `Our company number is ${HOSTUNICO_COMPANY.companyNumber}. You can find us on Companies House.` },
  { key: 'company-address', title: 'Our registered address', match: /\b(?:(?:your|company|registered|office|business) address|where are you (?:based|located)|where is your office)\b/i, say: `Our registered address is ${HOSTUNICO_COMPANY.registeredAddress}.` },
  { key: 'company-office-visits', title: 'Visiting our office or public access', match: /\b(?:visit|come (?:to|into)|drop (?:in|by)|pop (?:in|over)|meet).*(?:\boffice\b|\bgreen lanes\b|\byour premises\b|\bregistered address\b)|\bopen to (?:the )?public\b|\boffice\b.*\b(?:visit|drop by|open for visitors)\b/i, supersedes: ['property-visit'], say: "We're not open to the public. We operate remotely, with the on-site work happening at the properties." },
  { key: 'company-website', title: 'Our website', match: /\b(your website|company website|web address|find you online)\b/i, say: 'Our website is hostunico.com.' },
  { key: 'company-email', title: 'Contact the team', match: /\b(your email(?: address)?|company email|contact email|email (?:you|your team)|contact your team)\b/i, say: `You can reach our team at ${HOSTUNICO_COMPANY.supportEmail}.` },
  { key: 'company-experience', title: 'Our experience', match: /\b(your experience|how experienced|track record|how long have you|how many properties have you managed)\b/i, say: 'Our team has managed 200 properties over four years.' },
  { key: 'company-coverage', title: 'Where our properties are', match: /\b(which cities|what areas do you cover|where do you operate|where are (?:your|the) properties|where.*properties.*(?:located|based)|do you cover (?:manchester|liverpool))\b/i, say: 'Our properties are in Manchester and Liverpool.' },
  { key: 'owner-payouts', title: 'Who receives the money', match: /\b(who (?:gets|receives) (?:the )?(?:money|payouts?|booking (?:money|payments))|hold my money|paid directly|pay me directly)\b/i, say: 'Normally the booking platform pays you directly. Our management fee is handled separately, sometimes through an agreed Airbnb co-host payout.' },
] as const;

export const HOSTUNICO_COMPANY_KNOWLEDGE = `Verified Hostunico company knowledge. Use only the relevant fact to answer the caller, not a recital of this page.
${HOSTUNICO_COMPANY_ANSWERS.map((fact) => `${fact.title}: ${fact.say}`).join('\n')}
Use Hostunico for ordinary company-name questions. Give the registered company name only when they ask for the legal or registered name. Give the company number only when they ask for the number or Companies House verification. Do not add legal details to a brand answer.
The London address is the registered address. We are not open to the public. If asked to visit, say we operate remotely and on-site work happens at the properties. Do not invite a visit, offer office appointments, invent opening hours or claim an office in each operating city. Company verification: ${HOSTUNICO_COMPANY.registry}.
Experience means historical team experience, not 200 currently managed homes, verified reviews or a current occupancy result. Current portfolio count, individual references, opening hours, named local staff and a public telephone number are not supplied. Check with Hugo rather than inventing any of these.
Services: pricing and listing operations, booking/calendar coordination, guest communication and arrival guidance, cleaning/changeover coordination, agreed maintenance arrangements and owner reporting. The owner is buying a managed service supported by our system. Actual cleaners, linen, repairs, supplies, utilities, insurance and platform charges are separate costs. Pedro handles sales; Elsie and operations coordinate delivery; Hugo oversees the business and grants owner access.
Account and money: the owner keeps their Airbnb account; start with Airbnb and consider other channels later. Connecting Airbnb does not authorise a co-host payout. Booking payouts normally go to the owner. Confirmed co-host fee receipts are credited once against management fees. Do not promise a payout date. Pricing and VAT follow the current offer rules, not old website claims that software is free forever.
Onboarding: confirm property facts, authority and permissions; prepare furnishing, room essentials and photos; choose and test access; agree cleaning, linen and an emergency contact; accept the management agreement; submit for team review. Checklist completion alone is not approval to launch. Hugo grants portal access and the team confirms readiness and start date. Owner portal covers property preparation, evidence, agreement, bookings, income and operational updates. Management agreement: https://hostunico.com/management-agreement. Do not use /agreement, which is the consultant agreement.
Operations: cleaners work to agreed prices; routine supplies follow that arrangement. Elsie reviews cleaning photos and aims to finish at least one hour before agreed check-in. Physical service and spending authority depend on the property's recorded arrangements. Owner personal-use requests need team confirmation. Never promise unconfirmed 24/7 staff, universal geography or a launch date.
Remote delivery, confirmed by Hugo on 1 October 2026: Hostunico staff do not normally visit the property. Listings, pricing, bookings and guest messages are handled remotely. The onboarding checklist tells the owner what needs preparing; they can do it themselves or Hostunico can assign a cleaner to help. Physical setup, supplies and tradespeople are separate agreed property costs. A local cleaner does the physical cleaning, not Pedro or an AI. The usual guest-access options are a lockbox/key safe near the entrance with the key inside where fitting is permitted, or a nearby participating shop key-collection service. Guests collect the key and open the door themselves. Check the shop location, charges and opening hours; do not promise every town has a shop or that it opens all night. An existing suitable smart lock can be reviewed. Test every entrance and arrange spare keys and a local backup before launch. No guaranteed-rent offer, no lease taken by Hostunico and no reimbursement of empty nights or mortgage shortfalls. With no booking revenue the percentage management fee is zero; software from month two and standing property costs still apply.
Property permissions: check lease, mortgage, building rules, local short-let requirements, insurance and safety evidence. Do not promise a legal workaround or that an earnings estimate establishes permission. Report assumptions, studio proxy methodology, fee basis and annual limits are in the report; explain them accurately if asked, without adding them to the short first-call pitch.
Airbnb protection: published report refers to up to US$3 million host damage protection and US$1 million host liability insurance for eligible stays, separate programmes with terms and exclusions. Do not describe all damage as covered or sell this as Hostunico insurance.
Ending service: the published agreement allows cancellation within 14 days after acceptance by email or a portal offboarding request. If an early start was separately requested, proportionate agreed services provided may be payable. After that period, the team agrees the effective date, booking handover and final fees. Termination does not automatically cancel guest bookings. Do not invent a fixed notice period or promise a refund.
Complaints and privacy: contact ${HOSTUNICO_COMPANY.supportEmail} or use the owner portal; include the property and issue. The team records and reviews it, with management review if unresolved. Urgent safety/access incidents use the property's agreed urgent contact, not the complaints form. Shared report activity follows its published privacy controls and tracks the link, not a verified individual.
When a prospect corrects a fact or adds detail, answer their latest meaning and discard earlier assumptions. If your earlier suggestion no longer fits, give a fresh usable line. Keep company facts separate from facts about the prospect's property. Never fill an unknown with a plausible company claim.`;
