// The objections playbook the live coach carries (3 Oct 2026).
//
// GENERATED by scripts/hostunico-objections.mjs from the wk_objections table.
// Do not hand-edit: re-run the script with --write-module. A test fails if
// this file and the seeded table drift apart, or if any entry has a long dash.

export interface HostunicoObjection { category: string; objection: string; rebuttal: string; timesHeard: number }

export const HOSTUNICO_OBJECTIONS_GENERATED_AT = '2026-10-03';
export const HOSTUNICO_OBJECTIONS: readonly HostunicoObjection[] = [
  { category: 'Price', objection: 'Your fee is too expensive', rebuttal: 'Most managers charge somewhere between 15 and 20 percent, ours is 9 percent plus VAT. The report shows what you would keep.', timesHeard: 0 },
];

export const HOSTUNICO_OBJECTION_PLAYBOOK = `OBJECTION PLAYBOOK (real owner objections and the best answers, adapt to the call):
${HOSTUNICO_OBJECTIONS.map((o) => `- ${o.objection}: ${o.rebuttal}`).join('\n')}`;
