// The objections playbook the live coach carries (3 Oct 2026).
//
// GENERATED by scripts/hostunico-objections.mjs from the same data as the
// wk_objections seed (supabase/migrations/20261003000002_seed_hostunico_objections.sql).
// Do not hand-edit: re-run the script. tests/hostunico-objections.test.ts
// fails if this file and the seed drift apart, or if any entry has a long dash.

export interface HostunicoObjection { category: string; objection: string; rebuttal: string; timesHeard: number }

export const HOSTUNICO_OBJECTIONS_GENERATED_AT = "2026-10-03";
export const HOSTUNICO_OBJECTIONS_SEED = "20261003000002_seed_hostunico_objections.sql";
export const HOSTUNICO_OBJECTIONS: readonly HostunicoObjection[] = [
  { category: "Message only", objection: "They want you to leave a message or send it by text or email.", rebuttal: "Of course, I can text you the report link. Can I send it to this number?", timesHeard: 14 },
  { category: "Already have someone", objection: "They already work with someone or manage it themselves.", rebuttal: "That's fine. Most managers charge somewhere between 15 and 20 percent, ours is 9 percent plus VAT. Would it help to see the report so you can compare?", timesHeard: 8 },
  { category: "Not interested", objection: "They're not interested in short lets or the call.", rebuttal: "No problem, I'm not asking you to decide anything today. The report is free and just shows what your property could make on Airbnb compared with the rent. Can I send it over?", timesHeard: 8 },
  { category: "Website or call back", objection: "They want you to check the website or call back later.", rebuttal: "No problem, I'll keep it brief. I can send the free report over now and you can have a look when you've got a minute, then we can speak later if needed.", timesHeard: 8 },
  { category: "Different letting type", objection: "They want a tenant in place, not short-let management.", rebuttal: "That's fair, we only work where short lets are allowed. If it's not suitable, I'll leave it there, and if you ever want to compare it against the rent I can send the free report.", timesHeard: 7 },
  { category: "Busy now", objection: "They're busy and want you to call back or reply later.", rebuttal: "No problem, I'll keep it brief. I can send the report now and you can look at it when you've got time, then we can pick it up later if you want.", timesHeard: 6 },
  { category: "Future maybe", objection: "They want to look at it later or in the future.", rebuttal: "Of course, no problem. I can send the free report now, and if things change later you've got the figures to come back to.", timesHeard: 5 },
  { category: "Check with manager", objection: "They need to check with their manager or landlord first.", rebuttal: "Of course, no rush. I can send the free report over so they've got the figures to look at, and you can come back to me once you've spoken to them.", timesHeard: 4 },
  { category: "Location and support", objection: "They ask how you manage it from a distance or where you're based.", rebuttal: "We handle the guest messages and cleaners through our ops team, and the guest uses a lockbox or key collection. It's managed remotely, and you keep the booking income.", timesHeard: 4 },
  { category: "Price and fee", objection: "They think the fee is too high or it won't be worth it.", rebuttal: "I understand. Most managers charge somewhere between 15 and 20 percent, ours is 9 percent plus VAT. Software is free in month one, then 29 a month, and the report shows what you'd keep compared with your rent.", timesHeard: 4 },
  { category: "Wrong person or department", objection: "They say you've got the wrong person or department.", rebuttal: "No worries, I may have got wires crossed. I'm only on the short-let side, and I can send a free report if that helps.", timesHeard: 4 },
  { category: "Already letting or sold", objection: "The property is already let, sold, or unavailable right now.", rebuttal: "No worries, I can leave the report with you for when you're ready. It's just an estimate, so there's no pressure if the place isn't available now.", timesHeard: 3 },
  { category: "Building or licence blocks", objection: "The building, licence, or planning rules don't allow Airbnb.", rebuttal: "Fair enough, if the rules won't allow it then I'd leave it there. We only work where it's allowed, so no pressure from me.", timesHeard: 3 },
  { category: "Costs and estimate", objection: "They want net figures or worry about extra costs.", rebuttal: "I understand. Most managers charge somewhere between 15 and 20 percent, ours is 9 percent plus VAT. Software is free in month one, then 29 a month, and the report shows what you'd keep compared with your rent.", timesHeard: 3 },
  { category: "Long-term only", objection: "They only want a long-term tenancy or placement.", rebuttal: "I understand, a steady tenant is simple. The report just shows what the same property could make on Airbnb, so you can compare before you decide. Can I send it over?", timesHeard: 3 },
  { category: "Third-party or sub-let concern", objection: "They say they don't do third-party letting or sub-letting.", rebuttal: "No, we don't take it as a lease or rent-to-rent. The owner keeps their own Airbnb account and the booking income, and we just manage the short lets.", timesHeard: 3 },
  { category: "Wrong area", objection: "The property is not in the area you cover.", rebuttal: "We manage remotely, with local cleaners and our operations team. Our properties are in Manchester and Liverpool, so I'd confirm your area with Hugo before promising anything.", timesHeard: 3 },
  { category: "Income too low", objection: "They think the income won't be enough or occupancy is too low.", rebuttal: "That's fair, the report's only an estimate. It shows what the property could make on Airbnb versus the advertised rent, so you can judge whether it's worth a look.", timesHeard: 2 },
  { category: "No guaranteed rent", objection: "They want fixed rent or guaranteed income.", rebuttal: "No, we don't pay guaranteed rent or take a lease. You keep the booking income, so you benefit when it does well, but income isn't guaranteed.", timesHeard: 2 },
  { category: "Need proof", objection: "They want references or proof before they proceed.", rebuttal: "I get that, but I haven't got any reference details to give out on the phone. What I can do is send the free report so you can see the numbers first.", timesHeard: 1 },
  { category: "Upfront costs", objection: "They're worried about staging or bedding costs upfront.", rebuttal: "I understand. Most managers charge somewhere between 15 and 20 percent, ours is 9 percent plus VAT. Software is free in month one, then 29 a month, and the report shows what you'd keep compared with your rent.", timesHeard: 1 },
  { category: "Happy as is", objection: "We are happy as we are.", rebuttal: "That's fair, and nothing has to change. The free report just shows what the same property could earn on Airbnb, so you know your options. Shall I send it over?", timesHeard: 0 },
];

export const HOSTUNICO_OBJECTION_PLAYBOOK = `OBJECTION PLAYBOOK (real owner objections and the best answers, adapt to the call; a do-not-call request is never rebutted):
${HOSTUNICO_OBJECTIONS.map((o) => `- ${o.objection} ${o.rebuttal}`).join('\n')}`;
