import { HOSTUNICO_COMPANY } from './hostunico-company.ts';

// The answer bank retains the factual reference. These are the ready-to-say
// phone versions, shared by instant answers, Jev and the script quick answers.
// Price and software wording remain country-aware in hostunico-pricing.ts.
export const HOSTUNICO_SPOKEN_ANSWERS: Readonly<Record<string, string>> = {
  'vat': "It's 20% of our management fee, added on top. The management fee itself is 9% of the booking revenue.",
  'fee-basis': "It's 9% + VAT on the booking revenue, including any cleaning fee the guest pays, before the platform takes its fees. The actual cleaner and your property bills are separate costs.",
  'onboarding-fee': "No, there's no onboarding fee. If the property needs furniture, photos or repairs, we'd go through those costs with you separately.",
  'discount': "That's our standard offer. I can ask Hugo about your request, but I can't agree a different price myself on this call.",
  'too-expensive': "I understand. Let's look at what you'd keep after the costs and compare that with the rent you're asking now.",
  'hidden-costs': "There are property costs to allow for, like cleaning, platform fees, bills and repairs. Let's go through those in the report so you can see what you'd actually keep.",
  'guarantee': "No, we don't pay guaranteed rent. You keep the booking income, so you benefit when it does well. Income isn't guaranteed.",
  'account': "It's your Airbnb account. We help you set things up and manage it, but you keep the account. We'd start with Airbnb and look at other platforms after that.",
  'cleaning': "Our operations team arranges a local cleaner. We can assign one or check yours. Elsie reviews their photos, and you pay the agreed cleaning price separately.",
  'permission': "We'd need to check that your lease, mortgage and local rules allow it before we get started. I can take the property details and check anything that's unclear with Hugo.",
  'company-registration': `The registered company is ${HOSTUNICO_COMPANY.legalName}`,
  'company-number': `Our company number is ${HOSTUNICO_COMPANY.companyNumber}. You can find us on Companies House.`,
  'company-address': `Our registered address is ${HOSTUNICO_COMPANY.registeredAddress}.`,
  'company-office-visits': "We're not open to the public. We operate remotely, with the on-site work happening at the properties.",
  'company-website': "It's hostunico.com.",
  'company-email': `You can email the team at ${HOSTUNICO_COMPANY.supportEmail}.`,
  'company-experience': "Our team has managed 200 properties over four years.",
  'company-coverage': "Our properties are in Manchester and Liverpool.",
  'owner-payouts': "Normally, Airbnb or the booking platform pays you directly. Our management fee is separate. Sometimes that's through an agreed Airbnb co-host payout, but we'd go through that with you first.",
  'notenant': "I'm calling about helping you manage it for short and mid-term stays through Airbnb. Would you be open to having a look at an earnings comparison?",
  'identity': "I'm with Hostunico.",
  'stop': "Understood, thanks for letting me know. I'll record that so we don't keep following up.",
  'report': "Of course. I can send you a link, and it opens straight in your browser.",
  'service': "We handle the Airbnb listing, pricing, bookings and guest messages, and arrange cleaning. Guests let themselves in. You keep your Airbnb account.",
  'human-team': "The system helps the team do the work. I handle the sales side, Elsie coordinates operations, and Hugo oversees the business.",
  'owner-work': "You approve the setup and confirm permissions. We'll give you a checklist; you can prepare the property or we can assign a cleaner to help.",
  'existing-manager': "That's fine. We'd need to work around your current agreement and any bookings you've already got.",
  'self-manage': "That makes sense. If the day-to-day work is taking up too much of your time, that's where we can help.",
  'long-term': "I understand. A regular tenant might suit you better. The report just gives you a way to compare the two before you decide.",
  'think-about-it': "Of course, take your time with the numbers.",
  'not-now': "No problem, we can leave it for now.",
  'no-phone': "That's fine, we can put the details in writing.",
  'why-airbnb': "For the right property, short and mid-term stays can bring in more than a regular let. The report helps you compare that with the rent you're asking now.",
  'seasonality': "There can be quieter months. We keep reviewing the price and bookings, but income will vary with demand and how many nights are booked.",
  'guest-types': "It could be people visiting the area, travelling for work or needing somewhere temporarily. It depends on the location, so I wouldn't promise one particular type of guest.",
  'parties': "The team contacts the guest and enforces the house rules. Persistent problems go to the platform and agreed local contact. Immediate danger needs the emergency services.",
  'damage': "Airbnb offers up to US$3 million in host damage protection and US$1 million in host liability insurance for eligible stays, with terms and exclusions.",
  'property-insurance': "Yes, you'll still need to check your own policy allows short lets. Airbnb's protection doesn't replace your property insurance.",
  'guest-comms': "Elsie and the operations team handle guest messages and arrival instructions, so you don't have to.",
  'access': "Guests let themselves in with a lockbox near the entrance, with the key inside. If that isn't possible, we'd check a nearby key-collection shop and send the guest instructions.",
  'maintenance': "We arrange the agreed local tradesperson. We don't attend ourselves. Repairs are a separate cost, within the spending limit you've agreed.",
  'emergency': "For access problems, we use the agreed backup key or local contact. Immediate danger needs emergency services. We'd confirm local support and contact hours before launch.",
  'photos': "You can send us the photos you've got, and we'll check them. If anything's missing or professional photos are needed, we'd agree that separately. A photographer isn't automatically included.",
  'furnishing': "Yes, it needs to be ready for someone to stay. So beds, bedding, towels, furniture, and the kitchen and bathroom essentials shown in the listing. We'll give you a checklist for anything that's missing.",
  'linen': "You'll need bedding, towels and spare sets for changeovers. We agree quantities and laundry with the cleaner; buying and washing them are separate costs.",
  'existing-cleaner': "We can look at using your cleaner. We'd check their availability, price and access, and make sure they can follow the checklist and send photos after each clean.",
  'cleaning-checks': "The cleaner sends photos when they've finished, and Elsie checks them. They should finish at least an hour before check-in, so there's time to pick up anything that's been missed.",
  'utilities': "The property bills stay with you, separate from management. We'd include those when comparing what you'd keep, so you're not just looking at the booking income.",
  'personal-use': "We can look at the dates you want for yourself. The team just needs to check the calendar and any bookings already in place before confirming them.",
  'portal': "You'll have an owner portal where you can see bookings, income and updates about the property. We arrange your access during onboarding.",
  'payout-timing': "The booking platform sets that timing. We can check how your account is set up, but I wouldn't give you a payment date without checking.",
  'cohost': "You keep the account. If there's a co-host payout, we'd agree it with you first. Just connecting Airbnb doesn't authorise a payment split.",
  'other-platforms': "We'd start with Airbnb. Once the property and account are ready, we can look at adding other platforms.",
  'onboarding': "We give you owner access and a setup checklist, check permissions and the agreement, then set up Airbnb and test access before confirming launch.",
  'launch-time': "Let's see what's ready and what still needs doing. Once those checks are done, the team can confirm a realistic start date.",
  'agreement': "Yes, you can read it at hostunico.com/management-agreement. We can go through anything you're unsure about before you accept it.",
  'cooling-off': "There's a 14-day cancellation period. If you separately ask us to start early, you may need to pay for agreed services we've already provided.",
  'ending-service': "The agreement explains how to cancel. After the initial period, we'd agree the handover date with you and sort out the existing bookings and any final fees.",
  'existing-bookings': "We'd go through those bookings first. Starting or ending management doesn't automatically cancel the guests you've already booked in.",
  'report-method': "The report shows the research and assumptions behind the numbers. We can go through those with you and correct any property details that are missing or wrong.",
  'net-income': "That headline isn't what you'd take home. We'd need to allow for management and the property costs. The breakdown helps you see the difference.",
  'report-format': "It opens straight in your browser. There's no PDF to download and no app to install.",
  'not-owner': "Thanks for clarifying. We'd need to speak with the owner, or someone who can make that decision for them.",
  'already-let': "Thanks for letting me know. I'll note that it's no longer available.",
  'unsuitable-room': "Thanks for clarifying. We're focusing on whole studios and one-bedroom homes at the moment, so a room in a shared property wouldn't fit.",
  'references': "Let me check with Hugo which relevant references we can share. I'd rather get you something we can verify.",
  'complaint': `You can email ${HOSTUNICO_COMPANY.supportEmail} or raise it in the owner portal. Tell us the property and what's happened, and the team will record it and look into it.`,
  'legal-advice': "Your own adviser would need to help with your personal tax or legal position. I can explain our service and the checks we'd need for the property.",
  'remote-management': "We handle listings, pricing and guest messages online. A local cleaner handles changeovers, guests use self check-in, and we arrange agreed local tradespeople for repairs.",
  'property-visit': "No, we don't normally visit. We give you a setup checklist; you can do it yourself or we can assign a cleaner to help.",
  'access-and-cleaning': "Guests use a lockbox or local key-collection shop. A local cleaner handles changeovers, sends photos for us to check, and finishes at least an hour before check-in.",
  'access-lockbox-explained': "It's a small secure box with the key inside, usually fitted near the entrance. We send the guest the location and code, and they take the key and let themselves in.",
  'access-no-lockbox': "Then we'd look for a nearby shop that offers key collection. We'd check it's close enough and open when guests need to arrive before using it.",
  'access-keyshop': "You leave a key with a participating shop. Guests collect and return it using the service's instructions. We'd check opening hours and charges first.",
  'access-no-local-option': "We'd need a suitable lockbox, smart lock or confirmed local key handover before launching. We wouldn't rely on a shop service that isn't there.",
  'access-shop-hours': "If the shop's closed, that won't work for a late arrival. We'd need a lockbox, suitable smart lock or someone confirmed to hand over the key before offering that arrival time.",
  'access-smartlock': "We can look at using it. We'd test how guests get their code and make sure there's a backup if the lock or battery fails.",
  'access-installation': "You can arrange the fitting, or we can help find a suitable local person. The lockbox and installation are separate setup costs. We'd first check you're allowed to fit it where you want it.",
  'access-owner-present': "No, guests take the key from a lockbox and let themselves in. If you can't fit one, we'd check a nearby key-collection shop.",
  'access-keys-handover': "We'd sort out a key for guests and access for the cleaner during setup. You put the keys in the agreed lockbox or collection service, and we test the instructions before anyone stays.",
  'access-spare-keys': "Yes, it's worth having a spare and knowing who can get to it locally. That gives us a backup if a guest loses the key or the main access method fails.",
  'access-lost-key': "We check the code and instructions, then use the agreed spare key or local contact. Any locksmith cost follows your agreed spending arrangements.",
  'access-building-door': "We'd include that too. The guest needs to get through the building entrance as well as the flat door, so we'd sort out any fob or communal key and test the whole route.",
  'access-code-security': "We share the access details with the people who need them for the stay or clean. During setup, we'd agree who changes the code and how. We don't put it in the public listing.",
  'access-example': "For example, imagine a studio with a lockbox. The cleaner prepares it and leaves the key inside. We send the guest the code, and they let themselves in.",
  'setup-help': "Yes. We'll give you a checklist, and you can do the setup yourself or we can assign a cleaner to help. We'd agree the jobs and any purchases with you before starting.",
  'setup-costs': "You'd pay for furniture, equipment and any agreed setup work. We'd first go through what's missing, so you can decide what you're happy to spend.",
  'setup-checklist': "We'd check permissions, furniture, bedding, towels, safety, photos, guest access, cleaning and a local emergency contact. Then we'd work through what you've already got and list what's still needed.",
  'setup-abroad': "Yes, it can work if you live abroad. We'd still need local help for setup, cleaning and anything physical. We can assign a cleaner for setup and agree the key and repair arrangements with you.",
  'cleaning-cost': "You'd pay the cleaner at the agreed changeover price. If we charge the guest a cleaning fee, that contributes towards it. It's separate from management, and we'd include it in your cost breakdown.",
  'cleaning-frequency': "We arrange a clean between guest stays. For a longer stay, we can agree extra cleaning and its cost with you. Daily cleaning isn't automatically included.",
  'cleaning-supplies': "The cleaner can pick up the routine supplies they need under the arrangement we've agreed. They're a property cost, and the purchases should be recorded so you can see what's been bought.",
  'cleaning-backup': "The team needs to arrange cover and make sure the property's ready before the guest arrives. We'd check the local cover during setup, rather than promise a replacement somewhere we haven't checked.",
  'cleaning-problem': "If the photos show something's been missed, we ask the cleaner to put it right. If a guest reports it, the team checks what's happened and arranges a local response.",
  'linen-change': "We'd sort that out with the cleaner or a laundry service before starting. You need enough clean sets for changeovers, and washing or replacing them is a separate property cost.",
  'owner-no-income': "No bookings means no booking income, and we don't pay guaranteed rent. There's no percentage management fee, but the software fee from month two and your property bills still apply. We'd review pricing.",
  'owner-loss': "No, we don't cover your mortgage or a shortfall. That's why we'd compare the income after costs with your current rent before you decide. If bookings do well, you keep the benefit.",
  'rent-to-rent': "No, we wouldn't be your tenant. We manage it for you. It stays your property and your Airbnb account, with the booking money paid to you under the platform's arrangements.",
  'minimum-income': "No, we can't promise a minimum payment. What we can do is show you the estimated income and costs, then manage the pricing and bookings to improve the result.",
  'pricing-control': "We look after the nightly prices and review them against demand and bookings. We'd talk through your expectations and any price limits you want us to agree before starting.",
  'booking-length': "No, it doesn't have to be one-night stays. We work with short and mid-term stays. Longer bookings can mean fewer changeovers, and we'd choose the settings around the property and local rules.",
  'occupancy': "I can't promise a fixed number of booked nights. The report shows the occupancy assumption, and once it's live, we review the real bookings and adjust the pricing.",
  'guest-verification': "We use the guest details and checks available on the platform, make the house rules clear and look into any concerns. Those checks help, but they can't guarantee a guest won't cause a problem.",
  'cancellations': "That comes down to the cancellation policy on their booking. We handle the conversation and look at getting the dates booked again, but I wouldn't promise you'd keep the full payment after a cancellation.",
  'guest-late-checkout': "The team contacts the guest and coordinates with the cleaner. If they won't leave, we'd involve the platform and agreed local support.",
  'guest-complaint': "The team talks to the guest, checks what's wrong and works on a fix. If a refund comes up, we'd follow the platform rules and what you've authorised, rather than promise everyone a refund.",
  'property-safety': "We'd check what your property needs, including alarms and the relevant gas, electrical and fire checks. Anything missing goes on the setup list and needs sorting before the team approves launch.",
  'damage-claim': "The team gathers the photos and details and helps handle the claim through the platform. We'd need the evidence quickly because there are deadlines. Whether it's paid depends on the platform's terms and decision.",
  'bills-empty': "Yes, your regular property bills still need paying when it's empty, including mortgage or rent, utilities and insurance. We'd allow for that in the comparison, not just look at busy months.",
  'multiple-properties': "We can look at them together. We'd still check the numbers, permissions and setup for each one, rather than use one estimate for the whole lot.",
  'property-fit': "At the moment, we're focusing on whole studios and one-bedroom homes. We'd check the location, permissions, setup and numbers to see whether it makes sense for you.",
  'report-no-mobile': "No problem. I can send it to a mobile or by email. It's just a link that opens in your browser.",
  'report-missing': "Let me check the send status and the number or email we used. If that's right and it still hasn't arrived, I can check with you about resending it or trying the other way.",
  'report-wrong-facts': "Thanks for spotting that. I'll take the right details and have the report updated, so we're looking at the correct comparison before you decide.",
  'owner-approval': "We'd agree what can be spent during onboarding. Anything outside that comes back to you. We'd also agree what happens if there's an urgent problem that needs someone locally.",
  'deposits': "We'd need to check that against the platform and your setup. I wouldn't promise a cash deposit or say it guarantees any damage will be covered.",
  'listing-writing': "We help build and manage the listing in your Airbnb account, using the details and photos of your property. We'd make sure it clearly shows what guests get and how the place works.",
  'no-account': "That's fine, we'll guide you through creating your own account. You complete the identity and payout details, and we help with the listing and management access.",
  'calendar-double-booking': "We'd start with Airbnb. Before adding another platform, we'd connect and check the calendars so the same dates aren't sold twice. We'd also record any dates you want for yourself.",
  'existing-airbnb-reviews': "You keep your Airbnb account. We'd look at the listing you've already got and how to manage it. We don't normally ask you to delete it and start again.",
};
