import { hostunicoPriceCopy, hostunicoSoftwareCopy } from './hostunico-pricing.ts';
import { HOSTUNICO_COMPANY_ANSWERS } from './hostunico-company.ts';
import { HOSTUNICO_OPERATIONS_ANSWERS } from './hostunico-operations-answers.ts';

export type HostunicoAnswer = { key: string; title: string; match: RegExp; say: string; nextQuestion?: string; supersedes?: readonly string[] };

// Approved spoken answers. Property-specific numbers and actions stay with the
// conversational coach, which has the current lead, report and call state.
export const HOSTUNICO_ANSWERS: readonly HostunicoAnswer[] = [
  { key: 'price', title: 'The price', match: /\b(your fees?|management fee|what.*cost|commission|percentage|nine percent|9%|how much (?:is it|do you charge|does it cost))\b/i, say: hostunicoPriceCopy() },
  { key: 'software', title: 'Software from month two', match: /\b(software (?:fee|cost|price)|tools (?:fee|cost|price)|monthly subscription|free (?:first|one) month)\b/i, say: hostunicoSoftwareCopy() },
  { key: 'vat', title: 'VAT, only if asked', match: /\b(vat|value added tax)\b/i, say: 'VAT is 20% of our management fee, added on top. The management fee itself is 9% of booking revenue.' },
  { key: 'fee-basis', title: 'What the fee is based on', match: /\b(fee (?:based|calculated)|percentage of (?:what|profit|revenue)|gross or net|nine percent of what)\b/i, say: 'The 9% + VAT is based on booking revenue, including guest-paid cleaning, before platform fees. Actual cleaning and property costs are separate.' },
  { key: 'onboarding-fee', title: 'Setup charges', match: /\b(onboarding fee|setup fee|joining fee|upfront fee)\b/i, say: 'There is no onboarding fee. Any furnishing, photos, repairs or other property setup costs need to be agreed separately.' },
  { key: 'discount', title: 'Asked for a discount', match: /\b(discount|reduce your fee|negotiate.*fee|cheaper rate)\b/i, say: 'That is our standard offer. I can take your request to Hugo, but I cannot agree a different price on this call.' },
  { key: 'too-expensive', title: 'It feels expensive', match: /\b(too expensive|too much money|price is too high)\b/i, say: 'I understand. We can compare what you would keep after the costs with what you are asking now.', nextQuestion: 'Which cost concerns you most?' },
  { key: 'hidden-costs', title: 'Other costs to allow for', match: /\b(hidden (?:fees|costs)|extra charges|other costs|all.inclusive)\b/i, say: 'Cleaning, platform charges, utilities, repairs and other property costs are separate. We should check those against the report before you decide.' },
  { key: 'guarantee', title: 'Do you pay guaranteed rent?', match: /\b(guarantee|guaranteed|fixed rent|certain|definitely more)\b/i, say: 'No, we do not pay guaranteed rent or take a lease. You keep the booking income, so you benefit if the property earns more. Income is not guaranteed.' },
  { key: 'account', title: 'Their Airbnb account', match: /\b(whose account|my account|own account|airbnb account|keep.*account)\b/i, say: 'It stays in your Airbnb account. We start with Airbnb and help with the management setup, then look at other platforms.' },
  { key: 'cleaning', title: 'Who actually cleans the property?', match: /\b(who.*clean|cleaner|cleaning|laundry|supplies)\b/i, say: 'A local cleaner does the physical clean between stays. We can assign one, or review your existing cleaner. Elsie and the operations team coordinate the changeovers and review the photos. Cleaning is charged separately at the agreed price.' },
  { key: 'permission', title: 'Property permission', match: /\b(lease|mortgage|council|licen[cs]e|permission|90 nights|28 nights)\b/i, say: 'We need to check the local rules and your property permissions before agreeing a launch. I can confirm the details with Hugo.' },
  ...HOSTUNICO_COMPANY_ANSWERS,
  { key: 'notenant', title: 'Are you a tenant?', match: /\b(are you.*tenant|looking to rent|company let|rent it yourself)\b/i, say: 'I am calling about helping you manage short and mid-term lets through Airbnb. Would you be open to an earnings comparison?' },
  { key: 'identity', title: 'Who are you with?', match: /\b(who are you|who is this|who do you work for|who are you with|which company|what company|where are you calling from)\b/i, say: 'I am with Hostunico. We help owners manage short and mid-term lets through Airbnb.' },
  { key: 'stop', title: 'Respect their decision', match: /\b(stop calling|do not call|don.t call|remove.*number|not interested|leave me alone)\b/i, say: 'Understood, thank you for letting me know. I will record that so we do not keep following up.' },
  { key: 'report', title: 'Check the report status', match: /\b(send.*report|send.*details|text me|send.*text|send.*email)\b/i, say: 'Of course. I can send you a browser link to the report.' },
  { key: 'service', title: 'How does the service work?', match: /\b(what do you (?:do|handle|manage)|what.*service include|how (?:does (?:it|your service)|it) works?|tell me more|please explain|explain (?:it|to me)|go on)\b/i, say: 'We manage your Airbnb listing, prices, bookings and guest messages. Guests let themselves in using a lockbox or local key collection, and we coordinate a cleaner between stays. You keep your Airbnb account and receive the booking income under the platform arrangements.' },
  { key: 'human-team', title: 'People behind the system', match: /\b(is (?:it|this) (?:all|just|only) ai|real people|human team|only a robot)\b/i, say: 'Our system supports the operations team. Pedro handles sales, Elsie coordinates operations, and Hugo oversees the business.' },
  { key: 'owner-work', title: 'What do I need to do myself?', match: /\b(what do i (?:have|need) to do|how much work.*(?:me|owner))\b/i, say: 'You confirm permission to host, complete the account details and approve the setup. We give you a checklist for the property; you can do it yourself or we can assign a cleaner to help. Then we handle the day-to-day coordination.' },
  { key: 'existing-manager', title: 'Already has a manager', match: /\b(already (?:have|use).*manager|already managed|another management company)\b/i, say: 'Understood. Any change would need to respect your current agreement and bookings.', nextQuestion: 'Is there anything you would want handled differently?' },
  { key: 'self-manage', title: 'Already manages it themselves', match: /\b(manage it myself|do it myself|manage my own|already hosting)\b/i, say: 'That makes sense. We can help with the day-to-day work if it would save you time.', nextQuestion: 'Which part takes up the most time for you?' },
  { key: 'long-term', title: 'Prefers a long-term tenant', match: /\b(prefer.*long.term|want.*long.term tenant|rather.*tenant)\b/i, say: 'I understand. A regular tenancy may suit you better. The report lets you compare the options before deciding.' },
  { key: 'think-about-it', title: 'Wants time to think', match: /\b(think about it|talk to my partner|speak to my (?:partner|wife|husband)|discuss it with)\b/i, say: 'Of course. Take your time with the numbers.', nextQuestion: 'Is there anything you would like me to clarify first?' },
  { key: 'not-now', title: 'Maybe later', match: /\b(not now|maybe later|not ready yet|later in the year)\b/i, say: 'Understood. We can leave it for now.', nextQuestion: 'Would you prefer to come back to us when you are ready?' },
  { key: 'no-phone', title: 'Does not want a phone discussion', match: /\b(don.t want to discuss.*phone|not over the phone|prefer.*writing)\b/i, say: 'Of course. We can keep the details in writing.', nextQuestion: 'Would you prefer text or email?' },
  { key: 'why-airbnb', title: 'Why short lets?', match: /\b(why (?:airbnb|short.term|short lets)|benefit.*short.term)\b/i, say: 'Short and mid-term stays can create more earning potential for the right property. The report compares that option with your asking rent.' },
  { key: 'seasonality', title: 'Quiet months and empty nights', match: /\b(quiet months|low season|empty nights|no bookings|not booked|seasonal)\b/i, say: 'Income varies with demand, rates and occupied nights. We adjust pricing and review performance, but there can be quieter periods.' },
  { key: 'guest-types', title: 'Who would stay in my property?', match: /\b(who (?:are|would be) (?:the |my )?guests|who would stay|what (?:type|kind) of guests|business travellers|holidaymakers)\b/i, say: 'Depending on the location, it could be visitors, people travelling for work or people needing temporary accommodation. We work with short and mid-term stays rather than promise one particular type of guest.' },
  { key: 'parties', title: 'What about parties or noisy guests?', match: /\b(parties|party house|noisy guests|neighbour complaints)\b/i, say: 'We make the house rules clear and address reported noise with the guest. If it continues, the team escalates through the platform and the agreed local contact. Serious immediate safety problems need the emergency services.' },
  { key: 'damage', title: 'Airbnb protection', match: /\b(damage|aircover|liability insurance)\b/i, say: 'Airbnb has up to US$3 million host damage protection and US$1 million host liability insurance for eligible stays. Terms and exclusions apply.' },
  { key: 'property-insurance', title: 'The owner insurance policy', match: /\b(own insurance|property insurance|insurer|insurance policy)\b/i, say: 'You need to check that your property insurance allows this use. Airbnb protection does not replace your own policy.' },
  { key: 'guest-comms', title: 'Guest questions and arrivals', match: /\b(who (?:answers|replies|speaks).*guests|guest (?:messages|communication)|arrival (?:questions|guidance))\b/i, say: 'Elsie and the operations team handle guest communication and arrival guidance using the agreed arrangements for your property.' },
  { key: 'access', title: 'How do guests get into the property?', match: /\b(key safe|lock\s?box|smart lock|(?:guest |the )?access|who.*keys|guests?.*(?:get in|enter|open.*door)|who.*open.*door)\b/i, supersedes: ['service'], say: 'Usually guests let themselves in. We use a lockbox near the entrance with a key inside, where fitting one is possible. Otherwise we look for a nearby shop offering key collection. We send the guest clear instructions and test the access before launch.' },
  { key: 'maintenance', title: 'Who handles repairs?', match: /\b(repairs|maintenance|something breaks|broken boiler)\b/i, say: 'The team checks the problem with the guest and coordinates the agreed local tradesperson when a physical repair is needed. We do not attend ourselves. Repair costs are separate and follow your agreed spending authority.' },
  { key: 'emergency', title: 'What happens in an emergency?', match: /\b(emergency|emergencies|24.?7|middle of the night|urgent problem)\b/i, say: 'For an access or property problem, the team uses the backup key or local contact recorded during setup. Immediate danger needs the emergency services. We confirm the local response and contact hours before launch; I cannot promise unconfirmed 24-hour attendance.' },
  { key: 'photos', title: 'Who takes the property photos?', match: /\b(property photos|professional photos|photographer|new photos|take.*pictures)\b/i, say: 'You can provide clear, current photos. We review them and identify any missing views. If professional photography is needed, we agree that separately; a photographer is not automatically included in management.' },
  { key: 'furnishing', title: 'Does it need to be furnished?', match: /\b(furnished|furnishing|furniture|guest essentials|unfurnished)\b/i, say: 'Yes, it needs to be ready for someone to stay: suitable beds, bedding, towels, furniture and the kitchen and bathroom essentials shown in the listing. We give you a checklist of what is missing before launch.' },
  { key: 'linen', title: 'What bedding and towels do I need?', match: /\b(linen|towels|bed sheets|bedding)\b/i, say: 'You need bedding and towels for the advertised guest capacity, plus clean spare sets for changeovers. We agree quantities and laundry with the cleaner during setup. Buying and laundering them are separate property costs.' },
  { key: 'existing-cleaner', title: 'Can I keep my own cleaner?', match: /\b(my own cleaner|already have a cleaner|keep.*cleaner)\b/i, supersedes: ['cleaning'], say: 'We can work through that option with you. We need their availability, agreed price, access and ability to follow the checklist and send cleaning photos before confirming the arrangement.' },
  { key: 'cleaning-checks', title: 'How do you know the cleaner has done the job?', match: /\b(check.*cleaning|cleaning photos|check.*cleaner|before check.in)\b/i, supersedes: ['cleaning'], say: 'The cleaner sends photos after the changeover for Elsie to review. Cleaning should be finished at least one hour before the agreed check-in, leaving time to flag and fix anything missed.' },
  { key: 'utilities', title: 'Bills and supplies', match: /\b(who pays.*bills|utilities|electricity|water bills|broadband)\b/i, say: 'Utilities and property running costs remain separate from management. We should include them when comparing what you would keep.' },
  { key: 'personal-use', title: 'Using the property themselves', match: /\b(stay there myself|use it myself|personal use|block.*dates|stay.*family)\b/i, say: 'We can discuss dates you want for yourself. The team needs to check availability and existing bookings before confirming them.' },
  { key: 'portal', title: 'Seeing bookings and income', match: /\b(owner portal|owner dashboard|see my bookings|track.*income|see.*income)\b/i, say: 'The owner portal shows bookings, income and operational updates. The team arranges your access during onboarding.' },
  { key: 'payout-timing', title: 'When payments arrive', match: /\b(when.*(?:paid|payout|receive.*money)|how often.*(?:paid|payout))\b/i, say: 'The booking platform sets the payout timing. We can check the account arrangements, but I would not promise a payment date.' },
  { key: 'cohost', title: 'Co-host permission', match: /\b(co.host|payout split)\b/i, say: 'You keep the account. Any co-host payout needs your agreement; connecting Airbnb does not authorise it by itself.' },
  { key: 'other-platforms', title: 'Booking.com and other platforms', match: /\b(booking\.com|other platforms|other channels|vrbo)\b/i, say: 'We start with Airbnb, then review other platforms once the property and account setup are ready.' },
  { key: 'onboarding', title: 'What happens if I want to start?', match: /\b(onboarding|next steps|how do (?:i|we) (?:start|sign up))\b/i, say: 'We send you owner access and a setup checklist, confirm the property details and permissions, and go through the agreement. You prepare the property or we assign a cleaner to help. We set up Airbnb in your account, test access and confirm the launch date once it is ready.' },
  { key: 'launch-time', title: 'How soon it can go live', match: /\b(how (?:soon|quickly)|go live|start (?:tomorrow|next week)|launch date)\b/i, say: 'That depends on what is ready and what still needs doing. The team confirms the start date after the property checks.' },
  { key: 'agreement', title: 'Reading the agreement', match: /\b(management agreement|see.*contract|read.*terms|written agreement)\b/i, say: 'You can read the management agreement at hostunico.com/management-agreement. We can go through any questions before you accept it.' },
  { key: 'cooling-off', title: 'Cancellation in the first 14 days', match: /\b(cooling.off|14 days|fourteen days)\b/i, say: 'The agreement has a 14-day cancellation period. If you separately request an early start, agreed services already provided may be payable.' },
  { key: 'ending-service', title: 'Leaving the service', match: /\b(cancel.*(?:service|agreement)|end.*agreement|notice period|leave.*service|locked in)\b/i, say: 'The agreement sets out cancellation. After the initial period, we agree the handover date, existing bookings and final fees with you.' },
  { key: 'existing-bookings', title: 'Bookings already accepted', match: /\b(existing bookings|already.*bookings|bookings.*already)\b/i, say: 'We need to review those bookings before any change. Starting or ending management does not automatically cancel guest reservations.' },
  { key: 'report-method', title: 'How the report was made', match: /\b(how.*(?:calculate|work out).*figures|where.*numbers come from|report.*based on)\b/i, say: 'The report shows the research and assumptions behind the estimate. We can check those against your property and update any missing details.' },
  { key: 'net-income', title: 'Is the estimate what I keep?', match: /\b(net profit|take.home|what i keep|after all costs)\b/i, say: 'Check the breakdown in the report. The earnings headline is not take-home profit; management and property costs need to be allowed for.' },
  { key: 'report-format', title: 'Opening the report', match: /\b(pdf|download.*report|install.*app|how.*open.*report)\b/i, say: 'It opens as a page in your browser. You do not need to download a PDF or install an app.' },
  { key: 'not-owner', title: 'Needs the owner decision', match: /\b(not the owner|i.m the agent|i am the agent|owner.*decide)\b/i, say: 'Thanks for clarifying. We need the owner or someone authorised to make the decision.', nextQuestion: 'Would they be open to seeing the comparison?' },
  { key: 'already-let', title: 'The property is already let', match: /\b(already let|already rented|no longer available|tenant moved in)\b/i, say: 'Thanks for letting me know. I will note that the property is no longer available.' },
  { key: 'unsuitable-room', title: 'It turns out to be a room', match: /\b(only a room|just a room|shared house|house share)\b/i, say: 'Thanks for clarifying. We are focusing on whole studios and one-bedroom properties, so this would not fit.' },
  { key: 'references', title: 'Reviews and references', match: /\b(references|customer reviews|testimonials|speak to.*owner)\b/i, say: 'I can ask Hugo what relevant references we can share. I would rather confirm that than give you unverified examples.' },
  { key: 'complaint', title: 'A concern about the service', match: /\b(make a complaint|complaints process|unhappy.*service)\b/i, say: 'You can contact hello@unicohost.com or raise it in the owner portal. The team records the issue and arranges a review.' },
  { key: 'legal-advice', title: 'Personal tax or legal advice', match: /\b(income tax|tax return|tax advice|legal advice)\b/i, say: 'Your personal tax and legal position needs your own adviser. We can explain our service and the property checks we need.' },
  ...HOSTUNICO_OPERATIONS_ANSWERS,
];

export function hostunicoAnswerCopy(answer: HostunicoAnswer, country = 'GB') {
  if (answer.key === 'price') return hostunicoPriceCopy(country);
  if (answer.key === 'software') return hostunicoSoftwareCopy(country);
  return answer.say;
}

// Currency-sensitive answers come from the lead's country in the main rules.
export const HOSTUNICO_PREPARED_KNOWLEDGE = HOSTUNICO_ANSWERS
  .filter((answer) => !['price', 'software', 'report'].includes(answer.key))
  .map((answer) => `${answer.title}: ${answer.say}${answer.nextQuestion ? ` Useful question: ${answer.nextQuestion}` : ''}`)
  .join('\n');
