export const emailSignupCopy = {
  firstName: "First name",
  firstNamePlaceholder: "Maria",
  lastName: "Last name",
  lastNamePlaceholder: "Silva",
  email: "Email",
  emailPlaceholder: "you@email.com",
  whatsapp: "WhatsApp",
  termsPrefix: "I have read and accept the NextPubli ",
  termsLinkLabel: "Terms of Use",
  termsSuffix: ".",
  submit: "Create my account",
  submitting: "Sending code...",
  codeSentTitle: "Code sent! 📩",
  codeSentBody1: "We sent an 8-digit code to",
  codeSentBody2: "Enter the code below to confirm your email.",
  codeLabel: "8-digit code",
  codePlaceholder: "12345678",
  codeHint: "Nothing arrived? Check your spam folder or wait 1 minute.",
  verify: "Confirm and create account",
  verifying: "Confirming...",
  back: "← Go back and edit my details",
};
