export const emailSignupCopy = {
  firstName: "Nome",
  firstNamePlaceholder: "Maria",
  lastName: "Sobrenome",
  lastNamePlaceholder: "Silva",
  email: "Email",
  emailPlaceholder: "seu@email.com",
  whatsapp: "WhatsApp",
  termsPrefix: "Li e aceito os ",
  termsLinkLabel: "Termos de Uso",
  termsSuffix: " da NextPubli.",
  submit: "Criar minha conta",
  submitting: "Enviando código...",
  codeSentTitle: "Código enviado! 📩",
  codeSentBody1: "Enviamos um código de 8 dígitos para",
  codeSentBody2: "Digite o código abaixo para confirmar seu email.",
  codeLabel: "Código de 8 dígitos",
  codePlaceholder: "12345678",
  codeHint: "Não chegou? Confira a caixa de spam ou aguarde 1 minuto.",
  verify: "Confirmar e criar conta",
  verifying: "Confirmando...",
  back: "← Voltar e corrigir meus dados",
};
