// AUTO-GENERATED by scripts/gen-captions.mjs from pedro.srt — retimed to whisper words (1.2x).
export interface Caption { start: number; end: number; lines: string[] }
export const CAPTIONS: Caption[] = [
  {
    "start": 0.0,
    "end": 0.91,
    "lines": [
      "Quick video."
    ]
  },
  {
    "start": 1.51,
    "end": 4.17,
    "lines": [
      "I'll show you how your",
      "competitors are making more"
    ]
  },
  {
    "start": 4.17,
    "end": 7.45,
    "lines": [
      "money — just because they",
      "rank higher on Google."
    ]
  },
  {
    "start": 8.15,
    "end": 11.41,
    "lines": [
      "Have a look… these are the",
      "businesses in your area."
    ]
  },
  {
    "start": 11.75,
    "end": 13.99,
    "lines": [
      "The ones at the top get all",
      "the calls."
    ]
  },
  {
    "start": 14.53,
    "end": 19.95,
    "lines": [
      "Scroll down… Down… Down…",
      "Down… Down,"
    ]
  },
  {
    "start": 19.95,
    "end": 23.09,
    "lines": [
      "and there you are, near the",
      "bottom."
    ]
  },
  {
    "start": 23.37,
    "end": 26.43,
    "lines": [
      "So the best jobs go to the",
      "ones up top."
    ]
  },
  {
    "start": 26.77,
    "end": 27.71,
    "lines": [
      "Simple as that."
    ]
  },
  {
    "start": 27.71,
    "end": 30.69,
    "lines": [
      "And the only reason they're",
      "up there is more reviews…"
    ]
  },
  {
    "start": 31.27,
    "end": 32.67,
    "lines": [
      "Don't take my word for it —",
      "this is"
    ]
  },
  {
    "start": 32.67,
    "end": 34.23,
    "lines": [
      "Google's own page: 'More",
      "reviews"
    ]
  },
  {
    "start": 34.23,
    "end": 36.69,
    "lines": [
      "and positive ratings can",
      "improve your business's"
    ]
  },
  {
    "start": 36.69,
    "end": 39.67,
    "lines": [
      "local ranking.' More",
      "reviews, higher up."
    ]
  },
  {
    "start": 39.95,
    "end": 41.61,
    "lines": [
      "Higher up, more jobs."
    ]
  },
  {
    "start": 42.21,
    "end": 44.11,
    "lines": [
      "So why isn't it happening",
      "for you?"
    ]
  },
  {
    "start": 44.47,
    "end": 46.77,
    "lines": [
      "Soon as you finish a job,",
      "the customer"
    ]
  },
  {
    "start": 46.77,
    "end": 48.09,
    "lines": [
      "forgets to leave a review."
    ]
  },
  {
    "start": 48.57,
    "end": 50.91,
    "lines": [
      "You're onto the next one,",
      "they get on with their"
    ]
  },
  {
    "start": 50.91,
    "end": 56.13,
    "lines": [
      "day… and that five-star",
      "review never happens."
    ]
  },
  {
    "start": 56.13,
    "end": 58.27,
    "lines": [
      "So here's what we do, and",
      "it's"
    ]
  },
  {
    "start": 58.27,
    "end": 60.61,
    "lines": [
      "dead simple — three steps."
    ]
  },
  {
    "start": 61.25,
    "end": 63.59,
    "lines": [
      "One, we plug into whatever",
      "you run your"
    ]
  },
  {
    "start": 63.59,
    "end": 66.11,
    "lines": [
      "jobs on — your job software,",
      "your invoices,"
    ]
  },
  {
    "start": 66.43,
    "end": 68.07,
    "lines": [
      "even a simple spreadsheet."
    ]
  },
  {
    "start": 68.41,
    "end": 70.57,
    "lines": [
      "Or just send us your",
      "customer list."
    ]
  },
  {
    "start": 71.53,
    "end": 74.95,
    "lines": [
      "Two, soon as you finish a",
      "job, your"
    ]
  },
  {
    "start": 74.95,
    "end": 76.77,
    "lines": [
      "customer gets a friendly",
      "text"
    ]
  },
  {
    "start": 76.77,
    "end": 80.23,
    "lines": [
      "asking for a review — and it",
      "comes from YOUR business"
    ]
  },
  {
    "start": 80.23,
    "end": 83.49,
    "lines": [
      "name, sounds like you, and",
      "you approve"
    ]
  },
  {
    "start": 83.49,
    "end": 86.29,
    "lines": [
      "the wording first, before we",
      "start sending."
    ]
  },
  {
    "start": 86.29,
    "end": 88.13,
    "lines": [
      "Their name right on it, with",
      "a reminder"
    ]
  },
  {
    "start": 88.13,
    "end": 90.17,
    "lines": [
      "or two so it actually gets",
      "done."
    ]
  },
  {
    "start": 90.49,
    "end": 93.45,
    "lines": [
      "It's exactly how Google says",
      "to do it — real"
    ]
  },
  {
    "start": 93.45,
    "end": 96.87,
    "lines": [
      "customers, honest reviews,",
      "nothing dodgy."
    ]
  },
  {
    "start": 97.47,
    "end": 100.29,
    "lines": [
      "Three, that review lands on",
      "your Google, you"
    ]
  },
  {
    "start": 100.29,
    "end": 103.81,
    "lines": [
      "climb — and the calls start",
      "finding you."
    ]
  },
  {
    "start": 103.81,
    "end": 104.49,
    "lines": [
      "Here's the deal."
    ]
  },
  {
    "start": 105.09,
    "end": 107.29,
    "lines": [
      "Inside your first ten days",
      "you'll watch the first"
    ]
  },
  {
    "start": 107.29,
    "end": 109.57,
    "lines": [
      "reviews land — and as you",
      "climb over the"
    ]
  },
  {
    "start": 109.57,
    "end": 112.47,
    "lines": [
      "weeks after, the phone rings",
      "more and more."
    ]
  },
  {
    "start": 113.31,
    "end": 115.47,
    "lines": [
      "It costs one pound to find",
      "out:"
    ]
  },
  {
    "start": 115.99,
    "end": 117.99,
    "lines": [
      "ten days, cancel any time."
    ]
  },
  {
    "start": 118.13,
    "end": 120.83,
    "lines": [
      "After that it's ninety-nine",
      "a month, and we"
    ]
  },
  {
    "start": 120.83,
    "end": 123.57,
    "lines": [
      "handle the lot — the texts,",
      "the reminders,"
    ]
  },
  {
    "start": 123.57,
    "end": 126.49,
    "lines": [
      "and we even reply to every",
      "review for you."
    ]
  },
  {
    "start": 127.03,
    "end": 128.87,
    "lines": [
      "That's good for your Google",
      "ranking,"
    ]
  },
  {
    "start": 128.89,
    "end": 130.09,
    "lines": [
      "it makes you look more"
    ]
  },
  {
    "start": 130.09,
    "end": 131.67,
    "lines": [
      "professional to anyone",
      "checking you out,"
    ]
  },
  {
    "start": 131.67,
    "end": 133.51,
    "lines": [
      "and almost none of your",
      "competitors"
    ]
  },
  {
    "start": 133.51,
    "end": 135.35,
    "lines": [
      "bother — but we're",
      "different."
    ]
  },
  {
    "start": 136.23,
    "end": 138.79,
    "lines": [
      "Less than a single job pays",
      "for it."
    ]
  },
  {
    "start": 139.31,
    "end": 142.33,
    "lines": [
      "And we only work with five",
      "businesses per city, so"
    ]
  },
  {
    "start": 142.33,
    "end": 144.85,
    "lines": [
      "you're never competing with",
      "the one above you."
    ]
  },
  {
    "start": 145.01,
    "end": 147.23,
    "lines": [
      "Next time someone round your",
      "way needs the"
    ]
  },
  {
    "start": 147.23,
    "end": 149.73,
    "lines": [
      "job done — be the name they",
      "see first."
    ]
  },
  {
    "start": 150.35,
    "end": 152.17,
    "lines": [
      "Tap the button, and let's",
      "get you started."
    ]
  }
]
