export const copy = {
  title: "Campaign",
  schedule: {
    heading: "Schedule",
    addItem: "Add post",
    empty: "No posts in the campaign. Add the first one!",
    filterTypeAll: "All types",
    filterUpcoming: "Upcoming",
    filterPast: "Past",
    filterAll: "All",
    upcoming: "Upcoming",
    past: "Past",
    when: "When",
    type: "Type",
    brand: "Brand",
    caption: "Caption",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    confirmDelete:
      "Delete this post? Pending posts on the accounts will also be removed.",
  },
  itemModal: {
    addTitle: "Add post",
    editTitle: "Edit post",
    mediaType: "Post type",
    brand: "Brand",
    caption: "Caption",
    media: "Media",
    mediaUrl: "or paste the media URL: https://...",
    scheduledAt: "Date and time",
    timezone: "Timezone",
    collaborators: "Collaborators (up to 3, comma separated)",
    collaboratorsPlaceholder: "@brand, @profile2",
    firstComment: "First comment (optional)",
    firstCommentPlaceholder: "Comment posted automatically after the post",
    reelCover: "Reel cover (second of the video, optional)",
    storyNote:
      "Stories via the official Instagram API accept media only (image or 9:16 video). Captions, links, stickers, polls and music are not allowed by Meta for any tool.",
    save: "Save post",
    saving: "Saving...",
  },
  members: {
    heading: "Accounts in the campaign",
    addAccounts: "Add accounts",
    empty: "No accounts in the campaign yet.",
    name: "Name",
    instagram: "Instagram",
    addedAt: "Added on",
    startMode: "Start",
    startNow: "Immediate",
    startSchedule: "Schedule",
    remove: "Remove",
    confirmRemove:
      "Remove this account from the campaign? Its pending posts will be cancelled.",
    search: "Search account...",
  },
  addModal: {
    title: "Add accounts to the campaign",
    empty: "All connected accounts are already in the campaign.",
    connectedAt: "Connected on",
    startNowLabel: "Start now",
    startNowHint:
      "The campaign's first post will be published immediately for the selected accounts.",
    add: "Add to campaign",
    adding: "Adding...",
    selectAll: "Select all",
    deselectAll: "Deselect all",
  },
  settings: {
    edit: "Edit campaign",
    title: "Edit campaign",
    name: "Campaign name",
    description: "Description",
    brand: "Default brand",
    save: "Save",
    saving: "Saving...",
  },
  stats: {
    items: "posts",
    members: "accounts",
  },
  postTypes: {
    feed: "Feed",
    story_image: "Story (Image)",
    story_video: "Story (Video)",
    reel: "Reel",
    carousel: "Carousel",
  },
} as const;
