// One place that renders a signed working agreement as a printable document.
//
// Used by the public sign page (so the person keeps their own copy) and by the
// admin signed-agreements list (so Hugo can open, print or save any signature).
// Everything it renders comes from the snapshot stored at signing time, never
// from the live editable agreement row.

export interface SignedAgreementDoc {
  company: string;
  title: string;
  intro: string;
  terms: { heading: string; body: string }[];
  acks?: string[];
  fullName: string;
  email?: string | null;
  signedAt: string | Date;
  signaturePng?: string | null;
  /** Which agreement, and which revision of its wording, was signed. */
  slug?: string | null;
  version?: number | null;
}

const esc = (s: string) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** "10 August 2026, 14:05" in UK format. */
export function formatSignedAt(value: string | Date): string {
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  return d.toLocaleString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/** A complete, self-contained HTML page. Opens and prints cleanly on A4. */
export function buildSignedAgreementHtml(doc: SignedAgreementDoc): string {
  const sections = (doc.terms || [])
    .map(
      (t) =>
        `<section class="term"><h2>${esc(t.heading)}</h2><p>${esc(t.body)}</p></section>`,
    )
    .join('');

  const acks = (doc.acks || []).length
    ? `<section class="acks"><h2>Confirmed before signing</h2><ul>${(doc.acks || [])
        .map((a) => `<li>${esc(a)}</li>`)
        .join('')}</ul></section>`
    : '';

  const sig = doc.signaturePng
    ? `<img class="sig" src="${esc(doc.signaturePng)}" alt="Signature of ${esc(doc.fullName)}" />`
    : '<p class="muted">No signature image on file.</p>';

  const ref =
    doc.slug || doc.version
      ? `<p class="ref">Agreement reference: ${esc(doc.slug || '')}${doc.version ? ` (version ${doc.version})` : ''}</p>`
      : '';

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(doc.title)} - ${esc(doc.fullName)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: Inter, -apple-system, Segoe UI, Arial, sans-serif; color: #1A1A1A;
         line-height: 1.6; margin: 0; padding: 40px 24px; background: #F7F7F4; }
  .sheet { max-width: 760px; margin: 0 auto; background: #fff; border: 1px solid #E5E7EB;
           border-radius: 16px; padding: 40px; }
  .brand { font-weight: 800; font-size: 18px; letter-spacing: -0.01em; }
  h1 { font-size: 26px; margin: 6px 0 10px; letter-spacing: -0.02em; }
  .intro { color: #46514B; margin: 0 0 6px; }
  .term h2, .acks h2 { font-size: 16px; margin: 20px 0 4px; }
  .term p { margin: 0; color: #46514B; }
  .acks ul { margin: 6px 0 0; padding-left: 20px; color: #46514B; }
  .acks li { margin-bottom: 4px; }
  .signblock { margin-top: 32px; padding-top: 20px; border-top: 1px solid #E5E7EB; }
  .signblock div { margin-bottom: 4px; }
  .sig { display: block; margin-top: 12px; max-width: 320px; width: 100%;
         border: 1px solid #E5E7EB; border-radius: 10px; padding: 8px; background: #fff; }
  .muted, .ref { color: #9CA3AF; font-size: 12px; }
  .ref { margin-top: 18px; }
  .noprint { margin: 0 auto 16px; max-width: 760px; }
  .noprint button { font: inherit; font-size: 14px; font-weight: 600; color: #fff;
                    background: #3C5A87; border: 0; border-radius: 10px; padding: 10px 16px;
                    cursor: pointer; }
  @media print {
    body { background: #fff; padding: 0; }
    .sheet { border: 0; border-radius: 0; padding: 0; max-width: none; }
    .noprint { display: none !important; }
    .term, .acks { break-inside: avoid; }
    .signblock { break-inside: avoid; }
  }
</style></head>
<body>
<div class="noprint"><button onclick="window.print()">Print or save as PDF</button></div>
<div class="sheet">
  <div class="brand">${esc(doc.company)}</div>
  <h1>${esc(doc.title)}</h1>
  <p class="intro">${esc(doc.intro)}</p>
  ${sections}
  ${acks}
  <div class="signblock">
    <div><strong>Signed by:</strong> ${esc(doc.fullName)}</div>
    ${doc.email ? `<div><strong>Email:</strong> ${esc(doc.email)}</div>` : ''}
    <div><strong>Date signed:</strong> ${esc(formatSignedAt(doc.signedAt))}</div>
    ${sig}
  </div>
  ${ref}
  <p class="muted">Generated by ${esc(doc.company)} from the agreement text stored at the moment of signing.</p>
</div>
</body></html>`;
}

/** Open the signed copy in a new tab, ready to read or print. */
export function openSignedAgreement(doc: SignedAgreementDoc): void {
  const html = buildSignedAgreementHtml(doc);
  const w = window.open('', '_blank');
  if (w) {
    w.document.write(html);
    w.document.close();
    return;
  }
  // Pop-up blocked: fall back to a download so the copy is never lost.
  downloadSignedAgreement(doc);
}

/** Save the signed copy as a self-contained .html file. */
export function downloadSignedAgreement(doc: SignedAgreementDoc): void {
  const blob = new Blob([buildSignedAgreementHtml(doc)], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const who = doc.fullName.replace(/[^a-z0-9]+/gi, '-') || 'signed';
  a.download = `${doc.company.replace(/[^a-z0-9]+/gi, '-')}-Working-Agreement-${who}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
