// recipe.ts: timing, duration and the source registry. Pure, no Remotion.
//
// ON "MILLISECOND OFFSETS", because the brief asked for them and they need one
// plain sentence: sub-frame offsets do not exist in a rendered file. At 30fps a
// frame is 33.3ms, and an offset smaller than that changes nothing in the output
// pixels. So every offset here is expressed in FRAMES, and 33ms is the smallest
// step that means anything.

import { rng } from '../lib/human';
import { CTA_CAP_PX, HOOK_CAP_PX, TYPE_SCALE_MAX, TYPE_SCALE_MIN } from './fonts';
import rawSources from './sources.json';

/** The end card is a fixed 10 seconds on every video. */
export const CTA_FRAMES = 300;
export const FPS = 30;

/**
 * Bump when the visual recipe changes in a way that must regenerate everything.
 * It is folded into the seed, so bumping reshuffles every variant. That is a
 * deliberate "throw away the batch and re-render" switch, not something to
 * change casually.
 */
export const RECIPE_VERSION = 8;

export interface SourceSpec {
  readonly id: string;
  /** 720x1280. Plays inside the phone, 1:1 with SCREEN, never resampled. */
  readonly file: string;
  /** 1080x1920. Plays full bleed before the shrink. */
  readonly fullFile: string;
  readonly frames: number;
  readonly fps: number;
  /**
   * Frames where a cut would feel natural: scene changes and the edges of spoken
   * phrases, detected once at ingest. Ascending. May be empty, and an empty list
   * is not a failure, it just means the drop lands on its seeded target.
   */
  readonly beats: number[];
  /**
   * May this clip be mirrored? DEFAULTS TO FALSE. Set per clip by a human.
   *
   * Mirroring is the strongest cheap anti-cluster lever and it costs nothing,
   * which made "on by default" tempting. Checking the four demos settled it the
   * other way: three of them cannot be mirrored. One holds a bottle reading
   * "Lymphatic drainage", one a branded sachet, one carries burned-in captions.
   * A backwards product label on a video whose entire pitch is that AI footage
   * looks real does more damage than clustering ever would, and product UGC
   * nearly always has a label, a logo or a caption somewhere in it.
   *
   * So it fails safe and somebody switches it on per clip after watching the
   * clip through. ingest-sources carries the value forward, so the decision is
   * made once and survives every rebuild.
   *
   * NOTE that sources.json is an INPUT, not part of the recipe. Editing this
   * flag changes what that clip's variants look like without RECIPE_VERSION
   * moving, exactly as replacing the clip itself would. Re-render that clip.
   */
  readonly allowFlip?: boolean;
}

/**
 * Generated by scripts/ingest-sources.mjs, which reads the counts back out of
 * the encoded files with ffprobe. Never hand-edit it, and never trust the
 * durations of the originals: v2 arrives at 24fps and becomes 903 frames at 30.
 */
export const SOURCES = rawSources as SourceSpec[];
export const SOURCE_IDS = SOURCES.map((s) => s.id);

export function resolveSource(id: string): SourceSpec {
  const hit = SOURCES.find((s) => s.id === id);
  if (!hit) throw new Error(`unknown source: ${id}`);
  return hit;
}

/**
 * One salt per decision, and this is the single most important idea in the file.
 *
 * With a single sequential stream, inserting one new draw anywhere shifts every
 * decision after it. Add a background style in three months and all thousand
 * previously rendered variants silently change appearance, so the good ones can
 * never be reproduced. Salted per-channel streams mean a new channel is purely
 * additive and every existing channel is frozen forever.
 *
 * Add channels at the END of this object, never in the middle, and never reuse
 * a salt.
 */
export const CHANNELS = {
  palette: 0x9e3779b1,
  archetype: 0x85ebca6b,
  hookTiming: 0x165667b1,
  trim: 0x1b873593,
  cta: 0x27d4eb2f,
  drop: 0x2545f491,
  motion: 0x7feb352d,
  grade: 0x94d049bb,
  ambience: 0xbf58476d,
  type: 0xd6e8feb3,
} as const;

/**
 * How far a variant may zoom into its own clip, and why the number is this small.
 *
 * A zoom is the strongest cheap defence against clustering, because it moves
 * every pixel in the frame rather than repainting the edges, so block-matching
 * and perceptual hashes both break on it. It is also the one knob here that can
 * cost real sharpness, so it is capped by measurement rather than by feel: at
 * 1.045 the phone screen is showing 689 of the source's 720 columns stretched
 * across 720 output columns, a 4.5 percent upsample. Detail loss at that ratio
 * is below the level h264 quantisation already removes at crf 18. Anything past
 * about 8 percent starts to be visible on hard edges, which is why the cap is
 * where it is and not "a bit more to be safe".
 */
export const MAX_ZOOM = 1.045;

/**
 * The opening is treated differently from the rest, and there is one fact that
 * makes it possible: IT IS ALREADY BEING RESAMPLED.
 *
 * Filling a 1080x1920 canvas from a 720x1280 clip is a 1.5x upscale no matter
 * what, so geometric jitter in the opening is genuinely free. It is not free in
 * the phone act, where the clip maps one to one, which is why the rest of the
 * video is held to five quantised steps with 1.000 among them and the opening
 * is not held to anything.
 *
 * So the opening gets its OWN continuous zoom and crop, always at least 1.2
 * percent away from where the video ends up, and then drifts to meet it by the
 * moment the shrink finishes. Three things fall out of that:
 *
 *   - frame one is geometrically unique per file, always, with no exceptions and
 *     no pixel-identical fifth;
 *   - because it converges exactly, the handover from the upscaled twin to the
 *     untouched 720 file is still invisible;
 *   - a slow push over nine seconds is a technique, not a defect. It reads as
 *     intentional camera movement and if anything improves the opening.
 */
export const OPEN_ZOOM_MIN = 1.008;
export const OPEN_ZOOM_MAX = 1.055;
/** Minimum distance between the opening zoom and the resting zoom. */
export const OPEN_ZOOM_DRIFT = 0.012;

/**
 * The grade: a per-file contrast, saturation and brightness offset on the
 * opening, decaying to neutral across the shrink.
 *
 * Hugo asked for this specifically. It is implemented and it is capped at 1.5
 * percent, which is well below the level anybody notices without a reference
 * frame to compare against.
 *
 * IT IS THE WEAKEST OF THE THREE LEVERS AND THAT SHOULD BE SAID PLAINLY.
 * Perceptual hashing works on a DCT of the luminance thresholded at its own
 * median, so it is invariant to exactly this kind of global level shift by
 * design: a contrast tweak is close to free for a hash to see through. It does
 * change colour histograms and it does change every encoded byte, so it is not
 * nothing, but the geometry above is what does the work. It is capped here
 * rather than turned up because turning it up would cost real fidelity in
 * exchange for very little.
 */
export const MAX_GRADE = 0.015;

/**
 * The ambient bed. Must match COUNT and SECONDS in scripts/make-ambience.mjs;
 * a test fails if they drift, because a variant asking for bed 24 of 20 would
 * render with no audio bed at all and nothing would say so.
 */
export const AMBIENCE_COUNT = 20;
export const AMBIENCE_SECONDS = 180;

/**
 * How loud the bed sits, as a gain on a pool levelled to -31.7dB mean.
 *
 * 0.07 to 0.14 puts it between -55dB and -49dB, which is under the noise floor
 * of the source recordings themselves. Inaudible is the requirement.
 *
 * WHAT THIS DOES AND DOES NOT DO, because the gap matters. It changes every
 * audio sample, every encoded byte, the loudness statistics and the spectral
 * flatness of every file, and it smooths the cut into the end card. It does NOT
 * defeat audio fingerprinting, and nothing at this level could. Landmark
 * fingerprinting (Shazam, Content ID, Rights Manager) hashes the positions of
 * spectral PEAKS relative to each other, and was designed from the start to
 * survive a phone microphone in a loud bar. A bed 50dB under the voice is orders
 * of magnitude less interference than the case it was built for.
 *
 * The lever that would actually move a fingerprint is a 1 to 3 percent tempo
 * offset, because that shifts the peaks themselves in both time and frequency.
 * It cannot be done here: applied to the audio alone it drifts out of lip sync
 * within a minute, so it has to be applied to the whole clip at ingest, which
 * makes it a decision about the footage rather than a render setting.
 */
export const AMBIENCE_GAIN_MIN = 0.07;
export const AMBIENCE_GAIN_MAX = 0.14;

/**
 * The window the shrink into the phone aims for, as a FRACTION of the clip.
 *
 * It used to be an absolute 9 to 10 seconds, which meant a 60 second clip did
 * one sixth of the way in what a 30 second clip did one third of the way in.
 * The shrink is the structural midpoint of the video, so it belongs at the
 * middle of whatever the clip actually is: anywhere in 40 to 60 percent.
 *
 * That produces the variation for free, too. On a 60 second clip the drop can
 * land anywhere across a 12 second range, so one file breaks at 29.5s and the
 * next at 31s without anything else being asked of the seed.
 */
export const DROP_FRACTION_MIN = 0.4;
export const DROP_FRACTION_MAX = 0.6;
export const DROP_SNAP = 45;
/**
 * The clip plays clean for at least this long before the shrink. Only binds on
 * a very short clip, where 40 percent is not many frames.
 */
export const DROP_FLOOR = 150;
/**
 * A second hook is only worth showing if each line gets a decent run. Below this
 * many frames of text window the video keeps a single hook whatever the seed
 * says, which is most of them anyway.
 */
export const MIN_HOOK_WINDOW = 330;
/**
 * How far off a snapped beat a variant may sit, in frames.
 *
 * Snapping alone is not enough, and v3 is the proof: it is a long continuous
 * shot with music under it, so only ten beats were detected. Every variant
 * snapped to the same one, and 250 files all cutting at the same frame is
 * precisely the template signature the whole randomisation exists to avoid.
 *
 * Three frames is 100ms, comfortably inside the window a viewer reads as "on
 * the beat", so this buys seven landing positions per beat for nothing. It does
 * mean a drop is "near a beat" rather than exactly on one, which is what the
 * test asserts.
 */
export const DROP_JITTER = 3;
/** The phone segment has to last long enough to be the point of the video. */
export const MIN_PHONE_FRAMES = 150;

export interface Recipe {
  /**
   * Frames after the shrink completes before the first hook appears. 4 to 10.
   *
   * It used to be measured from frame 0, because the text used to start over the
   * opening. It does not any more: the opening plays completely clean, and the
   * text arrives with the phone.
   */
  readonly hookLeadFrames: number;
  /** Per-line entrance stagger, 2 to 5 frames. */
  readonly hookStagger: number;
  /**
   * How many hooks this video shows. ONE, or occasionally two.
   *
   * An earlier version rotated up to eight of them on a 2 to 3.5 second timer,
   * and Hugo was right to kill it. There is only one message here, and saying it
   * eight different ways dilutes it rather than reinforcing it; text that
   * changes every few seconds also competes with the clip for the attention it
   * is supposed to be holding. A line that simply sits there is a promise, and
   * once it is read it becomes furniture, which is exactly what you want.
   *
   * Two is the ceiling and it swaps once, at hookSwapFrame, which exists mostly
   * so a 60 second clip has something to change at its own halfway point.
   */
  readonly hookCount: number;
  /**
   * Output frame where the second hook takes over. 0 when there is only one.
   *
   * Absolute rather than a duration, so the swap sits at a sensible point in the
   * back half however long that is. There is never more than one swap.
   */
  readonly hookSwapFrame: number;
  /**
   * The output frame where the video stops filling the canvas and starts
   * shrinking into the phone.
   *
   * Seeded to 9 to 10 seconds, then snapped up to 1.5s to the nearest real beat
   * in this clip, so it lands on a scene change or a gap between phrases rather
   * than in the middle of a word. See dropFrameFor.
   */
  readonly dropFrame: number;
  /** How long the shrink takes. 12 to 30 frames, so 0.40s to 1.00s. */
  readonly dropFrames: number;
  /**
   * Which of three motion curves the shrink uses. All three cover the same
   * distance in the same time and none overshoots; they differ in where the
   * speed sits, which is what a human reads as the "feel" of an edit.
   */
  readonly dropEase: 0 | 1 | 2;
  /**
   * Mirror the clip horizontally.
   *
   * The single most effective anti-cluster transform available, and free: it is
   * a reflection, so not one pixel value changes, only its position. It defeats
   * pixel comparison and most perceptual hashing outright.
   *
   * Only ever true for a source whose manifest says allowFlip. A clip with
   * burned-in words, a logo, a watch on a wrist or a parting in someone's hair
   * looks obviously wrong mirrored, and that is a human judgement made once per
   * clip at ingest rather than guessed per render.
   */
  readonly flip: boolean;
  /** 1.000 to MAX_ZOOM. Exactly 1.000 for roughly a fifth of variants. */
  readonly zoom: number;
  /** Pan inside the zoom headroom, as a fraction of it. Never exposes an edge. */
  readonly panXf: number;
  readonly panYf: number;
  /**
   * Where the clip STARTS, before drifting to the values above. Continuous, so
   * no two files share an opening frame. See OPEN_ZOOM_MIN.
   */
  readonly openZoom: number;
  readonly openPanXf: number;
  readonly openPanYf: number;
  /** Per-file level offsets on the opening, each within MAX_GRADE of neutral. */
  readonly gradeContrast: number;
  readonly gradeSaturate: number;
  readonly gradeBrightness: number;
  /** Which of the ambient beds, where it starts in that bed, and how loud. */
  readonly ambienceIndex: number;
  readonly ambienceStartFrame: number;
  readonly ambienceGain: number;
  /**
   * Cap-height targets for this variant's hook and end card, in px.
   *
   * Both come from ONE scale in TYPE_SCALE_MIN..MAX, so they move together. This
   * is the only variation in the set that changes the SIZE of the type rather
   * than its colour, face or wording, which makes it one of the few that is
   * visible in a feed thumbnail.
   */
  readonly hookCapPx: number;
  readonly ctaCapPx: number;
  /** Frames before the end card text lands. 0 to 4. */
  readonly ctaLeadFrames: number;
  /**
   * Frames shaved off the head of the source. 0 to 12, so at most 0.4s.
   *
   * This is the whole of the per-file pixel variation, and it is free. Shifting
   * the head changes the content of every single frame relative to every other
   * variant, changes the file length, and costs nothing in quality because it is
   * a cut, not a filter. Capped at 12 so no variant eats the first word.
   *
   * The alternative that was considered and rejected was a sub-percent scale and
   * a few-pixel offset on the video. Both would work, and both would break the
   * 1:1 pixel mapping documented in geometry.ts, which is a real quality loss
   * traded for a difference the trim already provides.
   */
  readonly trimHeadFrames: number;
}

/**
 * FNV-1a 32. Stable across machines, node versions and architectures.
 *
 * Four properties, each load bearing:
 *  - stable, so re-running a batch overwrites files with identical content;
 *  - addressable, so "variant 47 of v2 is broken" maps to exactly one seed;
 *  - extensible, so raising the count from 4 to 250 leaves 0 to 3 untouched;
 *  - invalidatable, via RECIPE_VERSION, when that is actually what you want.
 */
export function seedFor(sourceId: string, variantIndex: number, recipeVersion: number): number {
  const key = `${recipeVersion}|${sourceId}|${variantIndex}`;
  let h = 0x811c9dc5;
  for (let i = 0; i < key.length; i++) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** A named channel's stream for a given seed. */
export function channel(seed: number, name: keyof typeof CHANNELS): () => number {
  const next = rng((seed ^ CHANNELS[name]) >>> 0);
  next();
  next();
  return next;
}

/**
 * Where the shrink lands, in output frames.
 *
 * A fixed ten seconds on every video is the thing Hugo objected to, and he was
 * right for a reason worth writing down: a cut that ignores the clip lands
 * mid-sentence or mid-gesture and reads as a glitch, while the same cut half a
 * second earlier on a phrase boundary reads as an edit. So the seeded target is
 * a suggestion, taken as a fraction of the clip, and the clip gets the final say
 * within 1.5s of it.
 *
 * Consumes exactly one draw from `dr`, always, whether or not a beat is found.
 * A branch that consumed a different number of draws would make every later
 * decision depend on whether this clip happened to have a beat nearby.
 */
function dropFrameFor(src: SourceSpec, dr: () => number, trimHead: number, body: number): number {
  const target = Math.round(
    body * (DROP_FRACTION_MIN + dr() * (DROP_FRACTION_MAX - DROP_FRACTION_MIN)),
  );
  // Drawn unconditionally, used only when a beat is found. A branch that
  // consumed a different number of draws would make every later decision depend
  // on whether this particular clip happened to have a beat nearby.
  const jitter = Math.round((dr() - 0.5) * 2 * DROP_JITTER);

  // Beats are indices into the source file. The head trim shifts the timeline,
  // so the beat we want is the one nearest the target PLUS the trim.
  const wanted = target + trimHead;
  let best = -1;
  let bestDistance = Infinity;
  for (const b of src.beats) {
    const d = Math.abs(b - wanted);
    // Strictly less than, over an ascending list, so ties resolve to the earlier
    // beat and the result cannot depend on iteration order.
    if (d < bestDistance) {
      bestDistance = d;
      best = b;
    }
  }

  const snapped = best >= 0 && bestDistance <= DROP_SNAP ? best - trimHead + jitter : target;
  const latest = Math.max(DROP_FLOOR, body - MIN_PHONE_FRAMES);
  return Math.min(Math.max(snapped, DROP_FLOOR), latest);
}

export function deriveRecipe(seed: number, sourceId: string): Recipe {
  const src = resolveSource(sourceId);
  const ht = channel(seed, 'hookTiming');
  const tr = channel(seed, 'trim');
  const ct = channel(seed, 'cta');
  const dr = channel(seed, 'drop');

  const trimHeadFrames = Math.floor(tr() * 13);
  const body = src.frames - trimHeadFrames;

  const hookLeadFrames = 4 + Math.floor(ht() * 7);
  const hookStagger = 2 + Math.floor(ht() * 4);

  const dropFrame = dropFrameFor(src, dr, trimHeadFrames, body);
  const dropFrames = 12 + Math.floor(dr() * 19);
  const dropEase = Math.floor(dr() * 3) as 0 | 1 | 2;

  const mo = channel(seed, 'motion');
  const flip = (src.allowFlip ?? true) && mo() < 0.5;
  // Quantised to five steps, and the bottom step is exactly 1. A continuous
  // range would mean no variant is ever pixel-exact, which throws away the one
  // guarantee the 1:1 layout was built for in exchange for nothing: a hash does
  // not care whether the zoom is 1.009 or 1.011.
  const zoomStep = Math.floor(mo() * 5);
  const zoom = 1 + (zoomStep / 4) * (MAX_ZOOM - 1);
  // Bounded to 80 percent of the headroom the zoom creates, so a pan can never
  // pull the frame edge into shot however the two are drawn.
  const panXf = (mo() - 0.5) * 1.6;
  const panYf = (mo() - 0.5) * 1.6;

  // The opening. Continuous, never quantised, and forced at least OPEN_ZOOM_DRIFT
  // away from the resting zoom so there is always something to drift, including
  // for the roughly one file in five that rests at exactly 1.000.
  let openZoom = OPEN_ZOOM_MIN + mo() * (OPEN_ZOOM_MAX - OPEN_ZOOM_MIN);
  if (Math.abs(openZoom - zoom) < OPEN_ZOOM_DRIFT) {
    // Push AWAY, in whichever direction has room, and never clamp afterwards.
    // Clamping after the push is what an earlier version did and it silently
    // undid the push: a value shoved below OPEN_ZOOM_MIN came back up to the
    // floor, which for a low resting zoom is nearer than the drift it was
    // supposed to guarantee.
    //
    // Both branches are provably in range. Up is zoom + 0.012, which is at
    // least 1.012 and is only past OPEN_ZOOM_MAX when the resting zoom is at
    // its own 1.045 ceiling; in that one case down is 1.033, comfortably above
    // OPEN_ZOOM_MIN.
    const up = zoom + OPEN_ZOOM_DRIFT;
    openZoom = up <= OPEN_ZOOM_MAX ? up : zoom - OPEN_ZOOM_DRIFT;
  }
  const openPanXf = (mo() - 0.5) * 1.6;
  const openPanYf = (mo() - 0.5) * 1.6;

  const gr = channel(seed, 'grade');
  const offset = () => (gr() - 0.5) * 2 * MAX_GRADE;
  const gradeContrast = 1 + offset();
  const gradeSaturate = 1 + offset();
  // Brightness is held to half the others. The eye is far more sensitive to a
  // shift in overall level than to one in contrast or colour.
  const gradeBrightness = 1 + offset() / 2;

  const am = channel(seed, 'ambience');
  const ambienceIndex = Math.floor(am() * AMBIENCE_COUNT);
  // The start offset is what stops the files that share a bed from sharing a
  // waveform. Bounded so the bed always outlasts the video: a bed that ran out
  // would either loop, which is a periodic artefact and therefore worse than no
  // bed at all, or fall silent halfway through.
  const total = src.frames - trimHeadFrames + CTA_FRAMES;
  const maxStart = Math.max(0, AMBIENCE_SECONDS * FPS - total);
  const ambienceStartFrame = Math.floor(am() * maxStart);
  const ambienceGain = AMBIENCE_GAIN_MIN + am() * (AMBIENCE_GAIN_MAX - AMBIENCE_GAIN_MIN);

  // Rounded to whole px because sizeForCap rounds anyway, so a fractional cap
  // buys nothing and only makes the recipe harder to read in a job file.
  const ty = channel(seed, 'type');
  const typeScale = TYPE_SCALE_MIN + ty() * (TYPE_SCALE_MAX - TYPE_SCALE_MIN);
  const hookCapPx = Math.round(HOOK_CAP_PX * typeScale);
  const ctaCapPx = Math.round(CTA_CAP_PX * typeScale);

  // One hook, or two on a third of videos. See the note on hookCount: this used
  // to run to eight and rotate, which was worse for the reason a slogan is worse
  // when you keep rewording it.
  //
  // The window has to be long enough for a second line to be worth showing. On a
  // 30 second clip the back half is about 15 seconds, so a swap gives each line
  // around 7; below MIN_HOOK_WINDOW there is not room for that and it stays at
  // one whatever the seed says.
  const textStart = dropFrame + dropFrames + hookLeadFrames;
  const window = body - textStart;
  const hookCount = window >= MIN_HOOK_WINDOW && ht() < 0.34 ? 2 : 1;
  // Placed at 45 to 65 percent of the window, so it is a genuine midpoint rather
  // than a change that lands just before the end card.
  const hookSwapFrame =
    hookCount === 2 ? textStart + Math.round(window * (0.45 + ht() * 0.2)) : 0;

  return {
    hookLeadFrames,
    hookStagger,
    hookCount,
    hookSwapFrame,
    ctaLeadFrames: Math.floor(ct() * 5),
    trimHeadFrames,
    dropFrame,
    dropFrames,
    dropEase,
    flip,
    zoom,
    panXf,
    panYf,
    openZoom,
    openPanXf,
    openPanYf,
    gradeContrast,
    gradeSaturate,
    gradeBrightness,
    ambienceIndex,
    ambienceStartFrame,
    ambienceGain,
    hookCapPx,
    ctaCapPx,
  };
}

/** Path of this variant's ambient bed, relative to public/. */
export function ambienceFile(r: Recipe): string {
  return `ambience/amb-${String(r.ambienceIndex).padStart(2, '0')}.m4a`;
}

/** Where the clip sits inside its window at a given moment. */
export interface ClipMotion {
  readonly zoom: number;
  readonly panXf: number;
  readonly panYf: number;
  readonly flip: boolean;
}

export const restMotion = (r: Recipe): ClipMotion => ({
  zoom: r.zoom,
  panXf: r.panXf,
  panYf: r.panYf,
  flip: r.flip,
});

export const openingMotion = (r: Recipe): ClipMotion => ({
  zoom: r.openZoom,
  panXf: r.openPanXf,
  panYf: r.openPanYf,
  flip: r.flip,
});

/**
 * The drift, where `u` runs 0 at the first frame to 1 the moment the shrink ends.
 *
 * Lerping the pan FRACTION rather than a pixel offset is what keeps this safe:
 * a fraction between two values in [-0.8, 0.8] is still in [-0.8, 0.8], and the
 * headroom is recomputed from the lerped zoom, so no intermediate position can
 * pull the frame edge into shot. Getting that wrong would show background
 * through the side of the clip for a few frames, in every file.
 */
export function motionAt(r: Recipe, u: number): ClipMotion {
  const k = Math.min(1, Math.max(0, u));
  const lerp = (a: number, b: number) => a + (b - a) * k;
  return {
    zoom: lerp(r.openZoom, r.zoom),
    panXf: lerp(r.openPanXf, r.panXf),
    panYf: lerp(r.openPanYf, r.panYf),
    flip: r.flip,
  };
}

/**
 * The CSS transform for the clip inside its window.
 *
 * translate before scale, so the offsets stay in unscaled units and the headroom
 * is simply (zoom - 1) / 2 of the element's own width.
 */
export function clipTransform(m: ClipMotion): string {
  const headroomPct = ((m.zoom - 1) / 2) * 100;
  const x = (m.panXf * headroomPct).toFixed(4);
  const y = (m.panYf * headroomPct).toFixed(4);
  return `translate(${x}%, ${y}%) scale(${m.zoom.toFixed(5)})${m.flip ? ' scaleX(-1)' : ''}`;
}

/**
 * The grade at strength `k`, 1 being the full per-file offset and 0 neutral.
 * Returns 'none' at neutral so the phone act carries no filter at all and its
 * pixels are never touched.
 */
export function gradeFilter(r: Recipe, k: number): string {
  const s = Math.min(1, Math.max(0, k));
  if (s === 0) return 'none';
  const at = (v: number) => (1 + (v - 1) * s).toFixed(5);
  return `contrast(${at(r.gradeContrast)}) saturate(${at(r.gradeSaturate)}) brightness(${at(r.gradeBrightness)})`;
}


/** Frames of source that actually play, after the head trim. */
export function bodyFrames(sourceId: string, recipe: Recipe): number {
  return resolveSource(sourceId).frames - recipe.trimHeadFrames;
}

/** Total output length. This is what calculateMetadata returns. */
export function totalFrames(sourceId: string, recipe: Recipe): number {
  return bodyFrames(sourceId, recipe) + CTA_FRAMES;
}

/**
 * Frames of audio fade before the cut into the silent end card.
 * Without it the cut clicks.
 */
export const AUDIO_FADE_FRAMES = 12;
