import type { PromptEntry } from "./types";

export const mockPrompts: PromptEntry[] = [
  {
    id: "1",
    handle: "aimikoda",
    name: "Aimi Koda",
    followers: 24500,
    style: "post",
    url: "https://x.com/aimikoda/status/1",
    postedAt: "2026-08-02",
    views: 41000,
    likes: 320,
    text: "Seedance 2.5 Prompt: 16:9, 30-second photoreal battle in clear daylight, one wide lens and one handheld pursuit shot, natural textures and clean HDR contrast.",
  },
  {
    id: "2",
    handle: "maxescu",
    name: "Max Escu",
    followers: 9800,
    style: "replies",
    url: "https://x.com/maxescu/status/2",
    postedAt: "2026-08-01",
    views: 12000,
    likes: 90,
    text: "Dancing With The AI Stars! Prompt below. Made with Seedance 2.5.",
  },
  {
    id: "4",
    handle: "bigessay",
    name: "Big Essay",
    followers: 900000,
    style: "likely",
    url: "https://x.com/bigessay/status/4",
    postedAt: "2026-08-03",
    views: 500000,
    likes: 900,
    text: "A long scene description with no label on it, camera drifting through a wet neon street at golden hour.",
  },
  {
    id: "3",
    handle: "tinyaccount",
    name: "Tiny Account",
    followers: 120,
    style: "named",
    url: "https://x.com/tinyaccount/status/3",
    postedAt: "2026-07-30",
    views: 400,
    likes: 3,
    text: "First Seedance 2.5 test, full prompt coming soon.",
  },
];
