export const globalCopy = {
  brand: "NextPubli",
  tagline: "Plataforma profissional de micro-influenciadores",
  nav: {
    home: "Início",
    calendar: "Calendário",
    analytics: "Analytics",
    settings: "Configurações",
  },
  adminNav: {
    overview: "Visão Geral",
    influencers: "Influenciadores",
    scheduler: "Agendador",
    messages: "Mensagens",
    brands: "Marcas",
    hotmart: "Hotmart",
    settings: "Configurações",
  },
  auth: {
    login: "Entrar",
    signup: "Cadastrar",
    logout: "Sair",
    forgotPassword: "Esqueceu a senha?",
  },
  common: {
    save: "Salvar",
    cancel: "Cancelar",
    next: "Próximo",
    back: "Voltar",
    loading: "Carregando...",
    error: "Algo deu errado",
    success: "Sucesso!",
    delete: "Excluir",
    edit: "Editar",
    search: "Buscar",
    filter: "Filtrar",
    noResults: "Nenhum resultado encontrado",
  },
  status: {
    connected: "Conectado",
    pending: "Pendente",
    active: "Ativo",
    inactive: "Inativo",
    published: "Publicado",
    scheduled: "Agendado",
    failed: "Falhou",
  },
  footer: {
    copyright: "© 2026 NextPubli. Todos os direitos reservados.",
  },
} as const;
