export const copy = {
  title: "Campanha",
  schedule: {
    heading: "Cronograma",
    addItem: "Adicionar publicação",
    empty: "Nenhuma publicação na campanha. Adicione a primeira!",
    filterTypeAll: "Todos os tipos",
    filterUpcoming: "Próximas",
    filterPast: "Passadas",
    filterAll: "Todas",
    upcoming: "Próxima",
    past: "Passada",
    when: "Quando",
    type: "Tipo",
    brand: "Marca",
    caption: "Legenda",
    actions: "Ações",
    edit: "Editar",
    delete: "Excluir",
    confirmDelete:
      "Excluir esta publicação? As publicações pendentes das contas também serão removidas.",
  },
  itemModal: {
    addTitle: "Adicionar publicação",
    editTitle: "Editar publicação",
    mediaType: "Tipo de post",
    brand: "Marca",
    caption: "Legenda",
    media: "Mídia",
    mediaUrl: "ou cole a URL da mídia: https://...",
    scheduledAt: "Data e hora",
    timezone: "Fuso horário",
    collaborators: "Colaboradores (até 3, separados por vírgula)",
    collaboratorsPlaceholder: "@marca, @perfil2",
    firstComment: "Primeiro comentário (opcional)",
    firstCommentPlaceholder: "Comentário publicado automaticamente após o post",
    reelCover: "Capa do Reel (segundo do vídeo, opcional)",
    storyNote:
      "Stories pela API oficial do Instagram aceitam só a mídia (imagem ou vídeo 9:16). Legenda, links, stickers, enquetes e música não são permitidos pela Meta para nenhuma ferramenta.",
    save: "Salvar publicação",
    saving: "Salvando...",
  },
  members: {
    heading: "Contas na campanha",
    addAccounts: "Adicionar contas",
    empty: "Nenhuma conta na campanha ainda.",
    name: "Nome",
    instagram: "Instagram",
    addedAt: "Adicionado em",
    startMode: "Início",
    startNow: "Imediato",
    startSchedule: "Cronograma",
    remove: "Remover",
    confirmRemove:
      "Remover esta conta da campanha? As publicações pendentes dela serão canceladas.",
    search: "Buscar conta...",
  },
  addModal: {
    title: "Adicionar contas à campanha",
    empty: "Todas as contas conectadas já estão na campanha.",
    connectedAt: "Conectou em",
    startNowLabel: "Começar agora",
    startNowHint:
      "A primeira publicação da campanha será publicada imediatamente para as contas selecionadas.",
    add: "Adicionar à campanha",
    adding: "Adicionando...",
    selectAll: "Selecionar todas",
    deselectAll: "Desmarcar todas",
  },
  settings: {
    edit: "Editar campanha",
    title: "Editar campanha",
    name: "Nome da campanha",
    description: "Descrição",
    brand: "Marca padrão",
    save: "Salvar",
    saving: "Salvando...",
  },
  stats: {
    items: "publicações",
    members: "contas",
  },
  postTypes: {
    feed: "Feed",
    story_image: "Story (Imagem)",
    story_video: "Story (Vídeo)",
    reel: "Reel",
    carousel: "Carrossel",
  },
} as const;
