-- ────────────────────────────────────────────────────────────────────────────
-- CRM Growth · Phase B — AI SMS auto-reply (warm-up)
-- When a lead texts back, the AI drafts/sends a reply using the closer's pitch,
-- with delay, max-replies, business hours, and auto-off controls. Storage stays
-- in wk_* tables; the reply text is generated by the shared Node LLM helper.
-- Idempotent / re-runnable.
-- ────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS wk_ai_reply_settings (
  id                      text PRIMARY KEY DEFAULT 'default',
  enabled                 boolean NOT NULL DEFAULT false,
  mode                    text NOT NULL DEFAULT 'draft'
    CONSTRAINT wk_ai_reply_mode_chk CHECK (mode IN ('draft', 'auto')),
  reply_delay_seconds     integer NOT NULL DEFAULT 45,
  max_replies_per_contact integer NOT NULL DEFAULT 5,
  hours_start             integer NOT NULL DEFAULT 0,   -- 0–23, 0/24 = always
  hours_end               integer NOT NULL DEFAULT 24,
  days                    text[] NOT NULL DEFAULT ARRAY['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
  timezone                text NOT NULL DEFAULT 'Europe/London',
  auto_off_on_human_reply boolean NOT NULL DEFAULT true,
  auto_off_on_booking     boolean NOT NULL DEFAULT true,
  handoff_keywords        text[] NOT NULL DEFAULT ARRAY['stop','human','agent','call me'],
  model                   text NOT NULL DEFAULT 'claude-sonnet-4-6',
  system_prompt           text NOT NULL DEFAULT
    'You are a friendly assistant warming up a property lead over SMS. Keep replies short (1–2 sentences), never use markdown, and guide them to call us back to speak with our team. Do not invent facts.',
  updated_by              uuid REFERENCES profiles(id) ON DELETE SET NULL,
  updated_at              timestamptz NOT NULL DEFAULT now()
);

-- Seed the singleton (disabled by default — Hugo turns it on after tuning the pitch).
INSERT INTO wk_ai_reply_settings (id) VALUES ('default') ON CONFLICT (id) DO NOTHING;

-- Per-contact AI controls.
ALTER TABLE wk_contacts
  ADD COLUMN IF NOT EXISTS ai_enabled       boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS ai_reply_count   integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_reply_last_at timestamptz;

-- Distinguish AI-generated outbound from human/agent outbound (for the
-- "human replied → auto-off" guard and for the draft-approval UI).
ALTER TABLE wk_sms_messages
  ADD COLUMN IF NOT EXISTS ai_generated boolean NOT NULL DEFAULT false;

-- updated_at trigger.
DROP TRIGGER IF EXISTS wk_ai_reply_settings_set_updated_at ON wk_ai_reply_settings;
CREATE TRIGGER wk_ai_reply_settings_set_updated_at
  BEFORE UPDATE ON wk_ai_reply_settings
  FOR EACH ROW EXECUTE FUNCTION wk_set_updated_at();

-- RLS: agents read settings, admins write.
ALTER TABLE wk_ai_reply_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS wk_ai_reply_settings_read ON wk_ai_reply_settings;
CREATE POLICY wk_ai_reply_settings_read ON wk_ai_reply_settings
  FOR SELECT TO authenticated USING (wk_is_agent_or_admin());
DROP POLICY IF EXISTS wk_ai_reply_settings_admin_all ON wk_ai_reply_settings;
CREATE POLICY wk_ai_reply_settings_admin_all ON wk_ai_reply_settings
  FOR ALL TO authenticated USING (wk_is_admin()) WITH CHECK (wk_is_admin());

-- Realtime so the draft/toggle UI updates live.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'wk_ai_reply_settings'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE wk_ai_reply_settings';
  END IF;
END $$;
